import { EventCategory, EventStatus } from "../types";

export interface MockEvent {
  id: string;
  title: string;
  category: EventCategory;
  status: EventStatus;
  venue: string;
  city: string;
  country: string;
  eventDate: bigint;
  description: string;
  coverImage: string;
  tags: string[];
  vendorId: string;
  createdAt: bigint;
  isDemo: true;
  fromPrice: number; // in INR paise (divide by 100 for INR display)
  isGlobal100?: boolean;
  isIndia100?: boolean;
  globalRank?: number;
  indiaRank?: number;
  voteCount?: number;
}

export interface MockArtist {
  id: string;
  name: string;
  category: "DJ" | "Celebrity" | "Band" | "Singer";
  nationality: string;
  flag: string;
  image: string;
  bookingFeeMin: number; // INR
  bookingFeeMax: number; // INR
  voteCount: number;
  genre?: string;
}

export interface MockLuxuryService {
  id: string;
  icon: string;
  name: string;
  description: string;
  fromPrice: number; // INR
  category: string;
}

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const DEMO_EVENTS: MockEvent[] = [
  // ── Global Top 100 ──────────────────────────────────────────────────────────
  {
    id: "demo-g1",
    title: "Tomorrowland 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "De Schorre Recreational Park",
    city: "Boom",
    country: "Belgium",
    eventDate: BigInt(now + 120 * day) * 1000000n,
    description:
      "The most iconic electronic music festival on Earth returns. Over 400,000 revellers from 200 countries unite for 3 weekends of world-class DJs, immersive stages, and breathtaking production.",
    coverImage: "",
    tags: ["EDM", "Festival", "Trance", "Techno"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1250000, // ₹12,500
    isGlobal100: true,
    globalRank: 1,
    voteCount: 142580,
  },
  {
    id: "demo-g2",
    title: "Ultra Music Festival Miami",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Bayfront Park",
    city: "Miami",
    country: "USA",
    eventDate: BigInt(now + 85 * day) * 1000000n,
    description:
      "Three days of boundary-pushing electronic music in Miami's iconic Bayfront Park. Ultra brings together the world's biggest DJs for an unforgettable weekend.",
    coverImage: "",
    tags: ["EDM", "Electronic", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1500000, // ₹15,000
    isGlobal100: true,
    globalRank: 2,
    voteCount: 98420,
  },
  {
    id: "demo-g3",
    title: "Coachella Valley Music & Arts",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Empire Polo Club",
    city: "Indio, California",
    country: "USA",
    eventDate: BigInt(now + 100 * day) * 1000000n,
    description:
      "The world's most famous arts and music festival returns to the California desert with an unparalleled headliner lineup, art installations, and cultural moments.",
    coverImage: "",
    tags: ["Music", "Arts", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1660000, // ₹16,600
    isGlobal100: true,
    globalRank: 3,
    voteCount: 187300,
  },
  {
    id: "demo-g4",
    title: "EDC Las Vegas 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Las Vegas Motor Speedway",
    city: "Las Vegas",
    country: "USA",
    eventDate: BigInt(now + 70 * day) * 1000000n,
    description:
      "Electric Daisy Carnival — the largest dance music festival in North America. 500 acres of neon carnival rides, 8 stages, and 140,000+ attendees per night.",
    coverImage: "",
    tags: ["EDM", "Festival", "House", "Trance"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1400000,
    isGlobal100: true,
    globalRank: 4,
    voteCount: 76500,
  },
  {
    id: "demo-g5",
    title: "Glastonbury Festival 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Worthy Farm",
    city: "Somerset",
    country: "UK",
    eventDate: BigInt(now + 130 * day) * 1000000n,
    description:
      "Britain's legendary performing arts festival celebrating 50+ years of iconic performances. Five stages, 200,000 attendees, and the legendary Pyramid Stage headliners.",
    coverImage: "",
    tags: ["Rock", "Pop", "Festival", "Arts"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 2000000, // ₹20,000
    isGlobal100: true,
    globalRank: 5,
    voteCount: 65700,
  },
  {
    id: "demo-g6",
    title: "Lollapalooza Chicago 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Grant Park",
    city: "Chicago",
    country: "USA",
    eventDate: BigInt(now + 95 * day) * 1000000n,
    description:
      "Four days of world-class music in Chicago's iconic Grant Park. 170+ acts, 8 stages, 100,000 fans per day — the definitive American music festival.",
    coverImage: "",
    tags: ["Rock", "Hip-Hop", "Electronic", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1100000,
    isGlobal100: true,
    globalRank: 6,
    voteCount: 54800,
  },
  {
    id: "demo-g7",
    title: "Sensation White Amsterdam",
    category: EventCategory.dj,
    status: EventStatus.published,
    venue: "Johan Cruijff Arena",
    city: "Amsterdam",
    country: "Netherlands",
    eventDate: BigInt(now + 50 * day) * 1000000n,
    description:
      "The world's most spectacular indoor electronic music event. 40,000 fans dressed in white fill Amsterdam's arena for an unforgettable night of music and light.",
    coverImage: "",
    tags: ["EDM", "Electronic", "Indoor", "Dance"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 900000,
    isGlobal100: true,
    globalRank: 7,
    voteCount: 43200,
  },
  {
    id: "demo-g8",
    title: "Creamfields UK 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Daresbury Estate",
    city: "Cheshire",
    country: "UK",
    eventDate: BigInt(now + 110 * day) * 1000000n,
    description:
      "Four days of electronic music in the UK's premier dance music festival. Creamfields brings 70,000 fans together for the biggest names in electronic music.",
    coverImage: "",
    tags: ["EDM", "Techno", "House", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1750000,
    isGlobal100: true,
    globalRank: 8,
    voteCount: 38900,
  },
  {
    id: "demo-g9",
    title: "ADE Amsterdam Dance Event",
    category: EventCategory.dj,
    status: EventStatus.published,
    venue: "Various Venues",
    city: "Amsterdam",
    country: "Netherlands",
    eventDate: BigInt(now + 140 * day) * 1000000n,
    description:
      "The world's largest club festival and leading electronic music conference. 5 days, 600+ events, 400,000+ visitors, and the most influential names in dance music.",
    coverImage: "",
    tags: ["Electronic", "Techno", "House", "Conference"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 500000,
    isGlobal100: true,
    globalRank: 9,
    voteCount: 29800,
  },
  {
    id: "demo-g10",
    title: "Champions League Final 2026",
    category: EventCategory.sports,
    status: EventStatus.published,
    venue: "Wembley Stadium",
    city: "London",
    country: "UK",
    eventDate: BigInt(now + 160 * day) * 1000000n,
    description:
      "Europe's most prestigious football tournament reaches its climax at Wembley. Two continental giants battle for the ultimate prize in front of 90,000 fans.",
    coverImage: "",
    tags: ["Football", "UEFA", "Champions League"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1250000,
    isGlobal100: true,
    globalRank: 10,
    voteCount: 221000,
  },

  // ── India Top 100 ───────────────────────────────────────────────────────────
  {
    id: "demo-i1",
    title: "Sunburn Goa Festival 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Vagator Beach",
    city: "Goa",
    country: "India",
    eventDate: BigInt(now + 60 * day) * 1000000n,
    description:
      "Asia's biggest electronic music festival returns to the golden shores of Goa. 72 hours of non-stop music across 3 stages with 100+ artists from around the globe.",
    coverImage: "",
    tags: ["EDM", "Beach", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 500000, // ₹5,000
    isIndia100: true,
    indiaRank: 1,
    voteCount: 89400,
  },
  {
    id: "demo-i2",
    title: "Coldplay: Music of the Spheres India Tour",
    category: EventCategory.concert,
    status: EventStatus.published,
    venue: "Narendra Modi Stadium",
    city: "Ahmedabad",
    country: "India",
    eventDate: BigInt(now + 90 * day) * 1000000n,
    description:
      "Coldplay's record-breaking world tour comes to India for an unforgettable night of music, light, and magic. Over 100,000 fans with LED wristbands transforming the stadium.",
    coverImage: "",
    tags: ["Coldplay", "Rock", "Concert"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 650000,
    isIndia100: true,
    isGlobal100: true,
    indiaRank: 2,
    globalRank: 15,
    voteCount: 154700,
  },
  {
    id: "demo-i3",
    title: "Lollapalooza India 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Mahalaxmi Race Course",
    city: "Mumbai",
    country: "India",
    eventDate: BigInt(now + 45 * day) * 1000000n,
    description:
      "India's edition of the iconic global festival brings international and domestic headliners together for two days of music, culture, and community in Mumbai.",
    coverImage: "",
    tags: ["Festival", "International", "Pop", "Rock"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 399000,
    isIndia100: true,
    indiaRank: 3,
    voteCount: 67200,
  },
  {
    id: "demo-i4",
    title: "NH7 Weekender Pune 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Shivaji Nagar Lawns",
    city: "Pune",
    country: "India",
    eventDate: BigInt(now + 35 * day) * 1000000n,
    description:
      "India's happiest music festival returns to Pune. Three stages, two days, indie rock, folk, electronic, and Bollywood — the most eclectic lineup in India.",
    coverImage: "",
    tags: ["Indie", "Folk", "Electronic", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 299000,
    isIndia100: true,
    indiaRank: 4,
    voteCount: 52300,
  },
  {
    id: "demo-i5",
    title: "Neon Pulse Music Festival",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "DY Patil Stadium",
    city: "Mumbai",
    country: "India",
    eventDate: BigInt(now + 7 * day) * 1000000n,
    description:
      "The biggest electronic music festival of the year featuring 50+ international DJs across 5 stages. Experience cutting-edge light shows and immersive art installations.",
    coverImage: "",
    tags: ["EDM", "Festival", "Electronic"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 390000,
    isIndia100: true,
    indiaRank: 5,
    voteCount: 44100,
  },
  {
    id: "demo-i6",
    title: "IPL Final 2026 — MI vs CSK",
    category: EventCategory.sports,
    status: EventStatus.published,
    venue: "Wankhede Stadium",
    city: "Mumbai",
    country: "India",
    eventDate: BigInt(now + 14 * day) * 1000000n,
    description:
      "Witness the ultimate cricket showdown at the iconic Wankhede Stadium. The biggest IPL season finale with world-class players competing for the championship title.",
    coverImage: "",
    tags: ["Cricket", "IPL", "Sports"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 150000,
    isIndia100: true,
    indiaRank: 6,
    voteCount: 198500,
  },
  {
    id: "demo-i7",
    title: "Magnetic Fields Festival 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Alsisar Mahal",
    city: "Rajasthan",
    country: "India",
    eventDate: BigInt(now + 75 * day) * 1000000n,
    description:
      "An intimate luxury festival set in a stunning desert palace. Electronic music meets royal Rajasthani hospitality — the most exclusive festival experience in India.",
    coverImage: "",
    tags: ["Electronic", "Luxury", "Festival", "Rajasthan"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 1200000,
    isIndia100: true,
    indiaRank: 7,
    voteCount: 28700,
  },
  {
    id: "demo-i8",
    title: "Diljit Dosanjh Dil-Luminati Tour",
    category: EventCategory.concert,
    status: EventStatus.published,
    venue: "Bharat Mandapam",
    city: "New Delhi",
    country: "India",
    eventDate: BigInt(now + 28 * day) * 1000000n,
    description:
      "The biggest Punjabi pop star returns to India for his landmark Dil-Luminati tour. High-energy performances, Punjabi hits, and a production like no other.",
    coverImage: "",
    tags: ["Punjabi", "Pop", "Concert", "Bollywood"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 350000,
    isIndia100: true,
    indiaRank: 8,
    voteCount: 112300,
  },
  {
    id: "demo-i9",
    title: "Bacardi NH7 Weekender Kolkata",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Eco Park",
    city: "Kolkata",
    country: "India",
    eventDate: BigInt(now + 55 * day) * 1000000n,
    description:
      "The NH7 Weekender expands to Kolkata with the same formula that made it India's favourite festival — diverse music, incredible food, and joyful community.",
    coverImage: "",
    tags: ["Indie", "Electronic", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 279000,
    isIndia100: true,
    indiaRank: 9,
    voteCount: 31500,
  },
  {
    id: "demo-i10",
    title: "VH1 Supersonic 2026",
    category: EventCategory.musicFestival,
    status: EventStatus.published,
    venue: "Aamby Valley City",
    city: "Pune",
    country: "India",
    eventDate: BigInt(now + 40 * day) * 1000000n,
    description:
      "India's premier EDM festival is back with the world's top electronic music artists. Three days of relentless music, incredible crowds, and unforgettable memories.",
    coverImage: "",
    tags: ["EDM", "Electronic", "Festival"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 450000,
    isIndia100: true,
    indiaRank: 10,
    voteCount: 41800,
  },

  // ── Additional events ────────────────────────────────────────────────────────
  {
    id: "demo-ex1",
    title: "Web3 Global Summit 2026",
    category: EventCategory.conference,
    status: EventStatus.published,
    venue: "Marina Bay Sands",
    city: "Singapore",
    country: "Singapore",
    eventDate: BigInt(now + 21 * day) * 1000000n,
    description:
      "Join 10,000+ blockchain innovators, DeFi pioneers, and Web3 builders at the world's largest decentralized technology conference.",
    coverImage: "",
    tags: ["Web3", "Blockchain", "Tech"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 2490000,
    isGlobal100: false,
    voteCount: 18900,
  },
  {
    id: "demo-ex2",
    title: "Grand Gala — Black Tie Evening",
    category: EventCategory.privateEvent,
    status: EventStatus.published,
    venue: "The Savoy",
    city: "London",
    country: "UK",
    eventDate: BigInt(now + 45 * day) * 1000000n,
    description:
      "An exclusive black-tie gala at London's legendary Savoy hotel. Live orchestra, celebrity guests, 5-course Michelin-star dinner, and charity auction.",
    coverImage: "",
    tags: ["Gala", "Exclusive", "Charity"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 6240000,
    voteCount: 8700,
  },
  {
    id: "demo-ex3",
    title: "Startup India Conclave 2026",
    category: EventCategory.conference,
    status: EventStatus.published,
    venue: "Bharat Mandapam",
    city: "New Delhi",
    country: "India",
    eventDate: BigInt(now + 35 * day) * 1000000n,
    description:
      "India's premier startup ecosystem event bringing together 5,000+ founders, investors, and mentors. Three days of panels, pitches, and networking sessions.",
    coverImage: "",
    tags: ["Startup", "Business", "Innovation"],
    vendorId: "demo-vendor",
    createdAt: BigInt(now) * 1000000n,
    isDemo: true,
    fromPrice: 890000,
    voteCount: 12400,
  },
];

export const MOCK_ARTISTS: MockArtist[] = [
  {
    id: "artist-1",
    name: "Martin Garrix",
    category: "DJ",
    nationality: "Netherlands",
    flag: "🇳🇱",
    image: "",
    bookingFeeMin: 20000000, // ₹2Cr
    bookingFeeMax: 50000000,
    voteCount: 87420,
    genre: "Progressive House",
  },
  {
    id: "artist-2",
    name: "Hardwell",
    category: "DJ",
    nationality: "Netherlands",
    flag: "🇳🇱",
    image: "",
    bookingFeeMin: 15000000,
    bookingFeeMax: 35000000,
    voteCount: 62100,
    genre: "Hardstyle / Big Room",
  },
  {
    id: "artist-3",
    name: "Tiësto",
    category: "DJ",
    nationality: "Netherlands",
    flag: "🇳🇱",
    image: "",
    bookingFeeMin: 25000000,
    bookingFeeMax: 60000000,
    voteCount: 94800,
    genre: "Progressive / Big Room",
  },
  {
    id: "artist-4",
    name: "Arijit Singh",
    category: "Singer",
    nationality: "India",
    flag: "🇮🇳",
    image: "",
    bookingFeeMin: 5000000,
    bookingFeeMax: 15000000,
    voteCount: 218900,
    genre: "Bollywood / Pop",
  },
  {
    id: "artist-5",
    name: "Badshah",
    category: "Singer",
    nationality: "India",
    flag: "🇮🇳",
    image: "",
    bookingFeeMin: 2500000,
    bookingFeeMax: 8000000,
    voteCount: 134700,
    genre: "Hip-Hop / Rap",
  },
  {
    id: "artist-6",
    name: "Dua Lipa",
    category: "Singer",
    nationality: "UK",
    flag: "🇬🇧",
    image: "",
    bookingFeeMin: 40000000,
    bookingFeeMax: 80000000,
    voteCount: 176500,
    genre: "Pop / Electronic",
  },
  {
    id: "artist-7",
    name: "The Weeknd",
    category: "Singer",
    nationality: "Canada",
    flag: "🇨🇦",
    image: "",
    bookingFeeMin: 50000000,
    bookingFeeMax: 120000000,
    voteCount: 243100,
    genre: "R&B / Pop",
  },
  {
    id: "artist-8",
    name: "DJ Snake",
    category: "DJ",
    nationality: "France",
    flag: "🇫🇷",
    image: "",
    bookingFeeMin: 8000000,
    bookingFeeMax: 20000000,
    voteCount: 71200,
    genre: "Electronic / Trap",
  },
  {
    id: "artist-9",
    name: "Sunidhi Chauhan",
    category: "Singer",
    nationality: "India",
    flag: "🇮🇳",
    image: "",
    bookingFeeMin: 1500000,
    bookingFeeMax: 5000000,
    voteCount: 98400,
    genre: "Bollywood",
  },
  {
    id: "artist-10",
    name: "Armand van Helden",
    category: "DJ",
    nationality: "USA",
    flag: "🇺🇸",
    image: "",
    bookingFeeMin: 4000000,
    bookingFeeMax: 12000000,
    voteCount: 31800,
    genre: "House / Electronic",
  },
];

export const MOCK_LUXURY_SERVICES: MockLuxuryService[] = [
  {
    id: "lux-1",
    icon: "✈️",
    name: "Private Jets",
    description: "Ultra-luxury private jet charters worldwide",
    fromPrice: 15000000, // ₹15L
    category: "Aviation",
  },
  {
    id: "lux-2",
    icon: "🚗",
    name: "Luxury Cars",
    description: "Rolls-Royce, Lamborghini, Bentley & more",
    fromPrice: 500000, // ₹5,000/day
    category: "Transport",
  },
  {
    id: "lux-3",
    icon: "🏨",
    name: "5-Star Hotels",
    description: "Curated luxury stays at iconic properties",
    fromPrice: 1500000, // ₹15,000/night
    category: "Accommodation",
  },
  {
    id: "lux-4",
    icon: "🛥️",
    name: "Yacht Charter",
    description: "Private yacht experiences & sea voyages",
    fromPrice: 10000000, // ₹1L/day
    category: "Marine",
  },
  {
    id: "lux-5",
    icon: "👑",
    name: "VIP Experiences",
    description: "Backstage passes, meet & greets, VIP lounges",
    fromPrice: 2500000, // ₹25,000
    category: "Experience",
  },
  {
    id: "lux-6",
    icon: "💎",
    name: "Models & Companions",
    description: "Professional models for events & parties",
    fromPrice: 1000000, // ₹10,000
    category: "Talent",
  },
];

export const CATEGORY_COLORS: Record<string, string> = {
  concert: "badge-concert",
  sports: "badge-sports",
  conference: "badge-conference",
  workshop: "badge-workshop",
  privateEvent: "badge-private",
  musicFestival: "badge-festival",
  dj: "badge-dj",
  celebrity: "badge-celebrity",
  luxuryParty: "badge-private",
  modelingAssignment: "badge-celebrity",
};

export const CATEGORY_LABELS: Record<string, string> = {
  concert: "Concert",
  sports: "Sports",
  conference: "Conference",
  workshop: "Workshop",
  privateEvent: "Private Event",
  musicFestival: "Music Festival",
  dj: "DJ",
  celebrity: "Celebrity",
  luxuryParty: "Luxury Party",
  modelingAssignment: "Modeling",
};

export const CATEGORY_GRADIENTS: Record<string, string> = {
  concert: "from-purple-900/80 via-purple-800/60 to-indigo-900/80",
  sports: "from-green-900/80 via-emerald-800/60 to-teal-900/80",
  conference: "from-blue-900/80 via-blue-800/60 to-cyan-900/80",
  workshop: "from-amber-900/80 via-orange-800/60 to-yellow-900/80",
  privateEvent: "from-pink-900/80 via-rose-800/60 to-red-900/80",
  musicFestival: "from-violet-900/80 via-fuchsia-800/60 to-purple-900/80",
  dj: "from-cyan-900/80 via-teal-800/60 to-sky-900/80",
  celebrity: "from-pink-900/80 via-rose-800/60 to-fuchsia-900/80",
  luxuryParty: "from-amber-900/80 via-yellow-800/60 to-orange-900/80",
  modelingAssignment: "from-rose-900/80 via-pink-800/60 to-fuchsia-900/80",
};
