/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const EventType = IDL.Variant({
  'dj' : IDL.Null,
  'workshop' : IDL.Null,
  'modelingAssignment' : IDL.Null,
  'musicFestival' : IDL.Null,
  'privateEvent' : IDL.Null,
  'conference' : IDL.Null,
  'luxuryParty' : IDL.Null,
  'sports' : IDL.Null,
  'celebrity' : IDL.Null,
});
export const Time = IDL.Int;
export const TicketType = IDL.Variant({
  'numberedSeat' : IDL.Null,
  'vipPackage' : IDL.Null,
  'generalAdmission' : IDL.Null,
  'timeSlot' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'customer' : IDL.Null,
  'superAdmin' : IDL.Null,
  'vendor' : IDL.Null,
});
export const User = IDL.Record({
  'isApproved' : IDL.Bool,
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'baseCurrency' : IDL.Text,
  'title' : IDL.Text,
  'endDate' : Time,
  'isPublished' : IDL.Bool,
  'basePriceINR' : IDL.Nat,
  'globalRank' : IDL.Opt(IDL.Nat),
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'isTop100India' : IDL.Bool,
  'description' : IDL.Text,
  'multiCurrencyEnabled' : IDL.Bool,
  'indiaRank' : IDL.Opt(IDL.Nat),
  'totalSeats' : IDL.Nat,
  'updatedAt' : Time,
  'isTop100Global' : IDL.Bool,
  'ticketType' : TicketType,
  'availableSeats' : IDL.Nat,
  'vendorId' : IDL.Principal,
  'promoVideoUrl' : IDL.Text,
  'bannerUrl' : IDL.Text,
  'location' : IDL.Text,
  'startDate' : Time,
  'supportedCurrencies' : IDL.Vec(IDL.Text),
  'eventType' : EventType,
});
export const ExchangeRates = IDL.Record({
  'inrToAed' : IDL.Float64,
  'inrToEur' : IDL.Float64,
  'inrToGbp' : IDL.Float64,
  'inrToUsd' : IDL.Float64,
});
export const AIItineraryStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
  'draft' : IDL.Null,
});
export const AIItineraryLog = IDL.Record({
  'id' : IDL.Nat,
  'status' : AIItineraryStatus,
  'eventId' : IDL.Opt(IDL.Text),
  'destination' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'travelDates' : IDL.Text,
  'itineraryData' : IDL.Text,
  'services' : IDL.Vec(IDL.Text),
});
export const VotingEntry = IDL.Record({
  'id' : IDL.Nat,
  'region' : IDL.Text,
  'voteCount' : IDL.Nat,
  'createdAt' : Time,
  'category' : IDL.Text,
  'artistName' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'refunded' : IDL.Null,
  'confirmed' : IDL.Null,
  'onHold' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'eventId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'confirmedAt' : IDL.Opt(IDL.Int),
  'cancelledAt' : IDL.Opt(IDL.Int),
  'ticketType' : TicketType,
  'totalAmountINR' : IDL.Nat,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'seatLockId' : IDL.Nat,
  'bookingToken' : IDL.Text,
  'stripeSessionId' : IDL.Opt(IDL.Text),
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'entityId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
  'userActor' : IDL.Principal,
});
export const EscrowPayoutStatus = IDL.Variant({
  'pending' : IDL.Null,
  'released' : IDL.Null,
  'rejected' : IDL.Null,
});
export const EscrowPayout = IDL.Record({
  'id' : IDL.Nat,
  'status' : EscrowPayoutStatus,
  'eventId' : IDL.Nat,
  'processedAt' : IDL.Opt(IDL.Int),
  'adminNote' : IDL.Opt(IDL.Text),
  'vendorId' : IDL.Principal,
  'amountINR' : IDL.Nat,
  'requestedAt' : IDL.Int,
});
export const FraudStatus = IDL.Variant({
  'autoHeld' : IDL.Null,
  'cleared' : IDL.Null,
  'flagged' : IDL.Null,
});
export const FraudLog = IDL.Record({
  'id' : IDL.Nat,
  'flags' : IDL.Vec(IDL.Text),
  'status' : FraudStatus,
  'bookingId' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'riskScore' : IDL.Nat,
});
export const PreloadedEventProfile = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Opt(IDL.Text),
  'title' : IDL.Text,
  'basePriceINR' : IDL.Nat,
  'globalRank' : IDL.Opt(IDL.Nat),
  'isTop100India' : IDL.Bool,
  'indiaRank' : IDL.Opt(IDL.Nat),
  'isActive' : IDL.Bool,
  'isTop100Global' : IDL.Bool,
  'promoVideoUrl' : IDL.Text,
  'bannerUrl' : IDL.Text,
  'location' : IDL.Text,
  'eventType' : EventType,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveVendor' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'createBooking' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        EventType,
        IDL.Text,
        Time,
        Time,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Nat,
        TicketType,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'createItinerary' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'createPreloadedProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Text,
        EventType,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
  'getExchangeRates' : IDL.Func([], [ExchangeRates], ['query']),
  'getItinerary' : IDL.Func([IDL.Nat], [IDL.Opt(AIItineraryLog)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat],
      [IDL.Vec(VotingEntry)],
      ['query'],
    ),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalRevenueINR' : IDL.Nat,
          'totalEvents' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'pendingEscrowPayouts' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'activeFraudAlerts' : IDL.Nat,
          'totalVendors' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getVendorStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'bookingsCount' : IDL.Nat,
          'revenueINR' : IDL.Nat,
          'eventsCount' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'listAuditLogs' : IDL.Func(
      [
        IDL.Opt(IDL.Principal),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Int),
      ],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'listEscrowPayouts' : IDL.Func([], [IDL.Vec(EscrowPayout)], ['query']),
  'listFraudLogs' : IDL.Func([], [IDL.Vec(FraudLog)], ['query']),
  'listMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listMyItineraries' : IDL.Func([], [IDL.Vec(AIItineraryLog)], ['query']),
  'listPreloadedProfiles' : IDL.Func(
      [],
      [IDL.Vec(PreloadedEventProfile)],
      ['query'],
    ),
  'listPublishedEvents' : IDL.Func(
      [
        IDL.Opt(EventType),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Bool),
        IDL.Opt(IDL.Bool),
      ],
      [IDL.Vec(Event)],
      ['query'],
    ),
  'lockSeat' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [IDL.Text], []),
  'publishEvent' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
  'rejectEscrowPayout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'releaseEscrowPayout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'requestEscrowPayout' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'reviewFraudFlag' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setEventTop100' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'setExchangeRates' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unpublishEvent' : IDL.Func([IDL.Nat], [], []),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'voteForArtist' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const EventType = IDL.Variant({
    'dj' : IDL.Null,
    'workshop' : IDL.Null,
    'modelingAssignment' : IDL.Null,
    'musicFestival' : IDL.Null,
    'privateEvent' : IDL.Null,
    'conference' : IDL.Null,
    'luxuryParty' : IDL.Null,
    'sports' : IDL.Null,
    'celebrity' : IDL.Null,
  });
  const Time = IDL.Int;
  const TicketType = IDL.Variant({
    'numberedSeat' : IDL.Null,
    'vipPackage' : IDL.Null,
    'generalAdmission' : IDL.Null,
    'timeSlot' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'customer' : IDL.Null,
    'superAdmin' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const User = IDL.Record({
    'isApproved' : IDL.Bool,
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Time,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'baseCurrency' : IDL.Text,
    'title' : IDL.Text,
    'endDate' : Time,
    'isPublished' : IDL.Bool,
    'basePriceINR' : IDL.Nat,
    'globalRank' : IDL.Opt(IDL.Nat),
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'isTop100India' : IDL.Bool,
    'description' : IDL.Text,
    'multiCurrencyEnabled' : IDL.Bool,
    'indiaRank' : IDL.Opt(IDL.Nat),
    'totalSeats' : IDL.Nat,
    'updatedAt' : Time,
    'isTop100Global' : IDL.Bool,
    'ticketType' : TicketType,
    'availableSeats' : IDL.Nat,
    'vendorId' : IDL.Principal,
    'promoVideoUrl' : IDL.Text,
    'bannerUrl' : IDL.Text,
    'location' : IDL.Text,
    'startDate' : Time,
    'supportedCurrencies' : IDL.Vec(IDL.Text),
    'eventType' : EventType,
  });
  const ExchangeRates = IDL.Record({
    'inrToAed' : IDL.Float64,
    'inrToEur' : IDL.Float64,
    'inrToGbp' : IDL.Float64,
    'inrToUsd' : IDL.Float64,
  });
  const AIItineraryStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const AIItineraryLog = IDL.Record({
    'id' : IDL.Nat,
    'status' : AIItineraryStatus,
    'eventId' : IDL.Opt(IDL.Text),
    'destination' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'travelDates' : IDL.Text,
    'itineraryData' : IDL.Text,
    'services' : IDL.Vec(IDL.Text),
  });
  const VotingEntry = IDL.Record({
    'id' : IDL.Nat,
    'region' : IDL.Text,
    'voteCount' : IDL.Nat,
    'createdAt' : Time,
    'category' : IDL.Text,
    'artistName' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'confirmed' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'eventId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'confirmedAt' : IDL.Opt(IDL.Int),
    'cancelledAt' : IDL.Opt(IDL.Int),
    'ticketType' : TicketType,
    'totalAmountINR' : IDL.Nat,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'seatLockId' : IDL.Nat,
    'bookingToken' : IDL.Text,
    'stripeSessionId' : IDL.Opt(IDL.Text),
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'entityId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
    'userActor' : IDL.Principal,
  });
  const EscrowPayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'released' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const EscrowPayout = IDL.Record({
    'id' : IDL.Nat,
    'status' : EscrowPayoutStatus,
    'eventId' : IDL.Nat,
    'processedAt' : IDL.Opt(IDL.Int),
    'adminNote' : IDL.Opt(IDL.Text),
    'vendorId' : IDL.Principal,
    'amountINR' : IDL.Nat,
    'requestedAt' : IDL.Int,
  });
  const FraudStatus = IDL.Variant({
    'autoHeld' : IDL.Null,
    'cleared' : IDL.Null,
    'flagged' : IDL.Null,
  });
  const FraudLog = IDL.Record({
    'id' : IDL.Nat,
    'flags' : IDL.Vec(IDL.Text),
    'status' : FraudStatus,
    'bookingId' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'riskScore' : IDL.Nat,
  });
  const PreloadedEventProfile = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Opt(IDL.Text),
    'title' : IDL.Text,
    'basePriceINR' : IDL.Nat,
    'globalRank' : IDL.Opt(IDL.Nat),
    'isTop100India' : IDL.Bool,
    'indiaRank' : IDL.Opt(IDL.Nat),
    'isActive' : IDL.Bool,
    'isTop100Global' : IDL.Bool,
    'promoVideoUrl' : IDL.Text,
    'bannerUrl' : IDL.Text,
    'location' : IDL.Text,
    'eventType' : EventType,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveVendor' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [], []),
    'confirmBooking' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'createBooking' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          EventType,
          IDL.Text,
          Time,
          Time,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Nat,
          TicketType,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'createItinerary' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'createPreloadedProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Text,
          EventType,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getEvent' : IDL.Func([IDL.Nat], [IDL.Opt(Event)], ['query']),
    'getExchangeRates' : IDL.Func([], [ExchangeRates], ['query']),
    'getItinerary' : IDL.Func([IDL.Nat], [IDL.Opt(AIItineraryLog)], ['query']),
    'getLeaderboard' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Nat],
        [IDL.Vec(VotingEntry)],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalRevenueINR' : IDL.Nat,
            'totalEvents' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'pendingEscrowPayouts' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'activeFraudAlerts' : IDL.Nat,
            'totalVendors' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getVendorStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'bookingsCount' : IDL.Nat,
            'revenueINR' : IDL.Nat,
            'eventsCount' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'listAuditLogs' : IDL.Func(
        [
          IDL.Opt(IDL.Principal),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Int),
        ],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'listEscrowPayouts' : IDL.Func([], [IDL.Vec(EscrowPayout)], ['query']),
    'listFraudLogs' : IDL.Func([], [IDL.Vec(FraudLog)], ['query']),
    'listMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listMyItineraries' : IDL.Func([], [IDL.Vec(AIItineraryLog)], ['query']),
    'listPreloadedProfiles' : IDL.Func(
        [],
        [IDL.Vec(PreloadedEventProfile)],
        ['query'],
      ),
    'listPublishedEvents' : IDL.Func(
        [
          IDL.Opt(EventType),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Bool),
          IDL.Opt(IDL.Bool),
        ],
        [IDL.Vec(Event)],
        ['query'],
      ),
    'lockSeat' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [IDL.Text], []),
    'publishEvent' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, UserRole], [], []),
    'rejectEscrowPayout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'releaseEscrowPayout' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'requestEscrowPayout' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'reviewFraudFlag' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setEventTop100' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Bool, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'setExchangeRates' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unpublishEvent' : IDL.Func([IDL.Nat], [], []),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'voteForArtist' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };