/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIItineraryLog {
  'id' : bigint,
  'status' : AIItineraryStatus,
  'eventId' : [] | [string],
  'destination' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'travelDates' : string,
  'itineraryData' : string,
  'services' : Array<string>,
}
export type AIItineraryStatus = { 'cancelled' : null } |
  { 'confirmed' : null } |
  { 'draft' : null };
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'entityId' : string,
  'timestamp' : bigint,
  'details' : string,
  'entityType' : string,
  'userActor' : Principal,
}
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'eventId' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'confirmedAt' : [] | [bigint],
  'cancelledAt' : [] | [bigint],
  'ticketType' : TicketType,
  'totalAmountINR' : bigint,
  'currency' : string,
  'quantity' : bigint,
  'seatLockId' : bigint,
  'bookingToken' : string,
  'stripeSessionId' : [] | [string],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'refunded' : null } |
  { 'confirmed' : null } |
  { 'onHold' : null };
export interface EscrowPayout {
  'id' : bigint,
  'status' : EscrowPayoutStatus,
  'eventId' : bigint,
  'processedAt' : [] | [bigint],
  'adminNote' : [] | [string],
  'vendorId' : Principal,
  'amountINR' : bigint,
  'requestedAt' : bigint,
}
export type EscrowPayoutStatus = { 'pending' : null } |
  { 'released' : null } |
  { 'rejected' : null };
export interface Event {
  'id' : bigint,
  'baseCurrency' : string,
  'title' : string,
  'endDate' : Time,
  'isPublished' : boolean,
  'basePriceINR' : bigint,
  'globalRank' : [] | [bigint],
  'createdAt' : Time,
  'tags' : Array<string>,
  'isTop100India' : boolean,
  'description' : string,
  'multiCurrencyEnabled' : boolean,
  'indiaRank' : [] | [bigint],
  'totalSeats' : bigint,
  'updatedAt' : Time,
  'isTop100Global' : boolean,
  'ticketType' : TicketType,
  'availableSeats' : bigint,
  'vendorId' : Principal,
  'promoVideoUrl' : string,
  'bannerUrl' : string,
  'location' : string,
  'startDate' : Time,
  'supportedCurrencies' : Array<string>,
  'eventType' : EventType,
}
export type EventType = { 'dj' : null } |
  { 'workshop' : null } |
  { 'modelingAssignment' : null } |
  { 'musicFestival' : null } |
  { 'privateEvent' : null } |
  { 'conference' : null } |
  { 'luxuryParty' : null } |
  { 'sports' : null } |
  { 'celebrity' : null };
export interface ExchangeRates {
  'inrToAed' : number,
  'inrToEur' : number,
  'inrToGbp' : number,
  'inrToUsd' : number,
}
export interface FraudLog {
  'id' : bigint,
  'flags' : Array<string>,
  'status' : FraudStatus,
  'bookingId' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'riskScore' : bigint,
}
export type FraudStatus = { 'autoHeld' : null } |
  { 'cleared' : null } |
  { 'flagged' : null };
export interface PreloadedEventProfile {
  'id' : bigint,
  'eventId' : [] | [string],
  'title' : string,
  'basePriceINR' : bigint,
  'globalRank' : [] | [bigint],
  'isTop100India' : boolean,
  'indiaRank' : [] | [bigint],
  'isActive' : boolean,
  'isTop100Global' : boolean,
  'promoVideoUrl' : string,
  'bannerUrl' : string,
  'location' : string,
  'eventType' : EventType,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type TicketType = { 'numberedSeat' : null } |
  { 'vipPackage' : null } |
  { 'generalAdmission' : null } |
  { 'timeSlot' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface User {
  'isApproved' : boolean,
  'principal' : Principal,
  'name' : string,
  'createdAt' : Time,
  'role' : UserRole,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'customer' : null } |
  { 'superAdmin' : null } |
  { 'vendor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VotingEntry {
  'id' : bigint,
  'region' : string,
  'voteCount' : bigint,
  'createdAt' : Time,
  'category' : string,
  'artistName' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveVendor' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'confirmBooking' : ActorMethod<[bigint, string], undefined>,
  'createBooking' : ActorMethod<[bigint, bigint, bigint, string], bigint>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createEvent' : ActorMethod<
    [
      string,
      string,
      EventType,
      string,
      Time,
      Time,
      bigint,
      Array<string>,
      boolean,
      bigint,
      TicketType,
      string,
      string,
      Array<string>,
    ],
    bigint
  >,
  'createItinerary' : ActorMethod<
    [[] | [string], string, string, Array<string>],
    bigint
  >,
  'createPreloadedProfile' : ActorMethod<
    [
      [] | [string],
      string,
      EventType,
      string,
      bigint,
      string,
      string,
      boolean,
      boolean,
      [] | [bigint],
      [] | [bigint],
    ],
    bigint
  >,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getEvent' : ActorMethod<[bigint], [] | [Event]>,
  'getExchangeRates' : ActorMethod<[], ExchangeRates>,
  'getItinerary' : ActorMethod<[bigint], [] | [AIItineraryLog]>,
  'getLeaderboard' : ActorMethod<
    [[] | [string], [] | [string], bigint],
    Array<VotingEntry>
  >,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'totalRevenueINR' : bigint,
      'totalEvents' : bigint,
      'totalBookings' : bigint,
      'pendingEscrowPayouts' : bigint,
      'totalUsers' : bigint,
      'activeFraudAlerts' : bigint,
      'totalVendors' : bigint,
    }
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [User]>,
  'getVendorStats' : ActorMethod<
    [],
    { 'bookingsCount' : bigint, 'revenueINR' : bigint, 'eventsCount' : bigint }
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllBookings' : ActorMethod<[], Array<Booking>>,
  'listAllUsers' : ActorMethod<[], Array<User>>,
  'listAuditLogs' : ActorMethod<
    [[] | [Principal], [] | [string], [] | [bigint], [] | [bigint]],
    Array<AuditLog>
  >,
  'listEscrowPayouts' : ActorMethod<[], Array<EscrowPayout>>,
  'listFraudLogs' : ActorMethod<[], Array<FraudLog>>,
  'listMyBookings' : ActorMethod<[], Array<Booking>>,
  'listMyItineraries' : ActorMethod<[], Array<AIItineraryLog>>,
  'listPreloadedProfiles' : ActorMethod<[], Array<PreloadedEventProfile>>,
  'listPublishedEvents' : ActorMethod<
    [
      [] | [EventType],
      [] | [string],
      [] | [bigint],
      [] | [bigint],
      [] | [boolean],
      [] | [boolean],
    ],
    Array<Event>
  >,
  'lockSeat' : ActorMethod<[bigint, [] | [string]], string>,
  'publishEvent' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string, string, UserRole], undefined>,
  'rejectEscrowPayout' : ActorMethod<[bigint, string], undefined>,
  'releaseEscrowPayout' : ActorMethod<[bigint, string], undefined>,
  'requestEscrowPayout' : ActorMethod<[bigint], bigint>,
  'reviewFraudFlag' : ActorMethod<[bigint, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[string, string], undefined>,
  'setEventTop100' : ActorMethod<
    [bigint, boolean, boolean, [] | [bigint], [] | [bigint]],
    undefined
  >,
  'setExchangeRates' : ActorMethod<[number, number, number, number], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unpublishEvent' : ActorMethod<[bigint], undefined>,
  'updateEvent' : ActorMethod<
    [bigint, string, string, string, bigint, string, string, Array<string>],
    undefined
  >,
  'voteForArtist' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];