/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventCategory = IDL.Variant({
  'concert' : IDL.Null,
  'workshop' : IDL.Null,
  'privateEvent' : IDL.Null,
  'conference' : IDL.Null,
  'sports' : IDL.Null,
});
export const Time = IDL.Int;
export const AddEventArgs = IDL.Record({
  'id' : IDL.Text,
  'baseCurrency' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'multiCurrencyEnabled' : IDL.Bool,
  'coverImage' : IDL.Text,
  'vendorId' : IDL.Text,
  'category' : EventCategory,
  'eventDate' : Time,
  'supportedCurrencies' : IDL.Vec(IDL.Text),
});
export const EventStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'published' : IDL.Null,
  'completed' : IDL.Null,
  'draft' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Text,
  'status' : EventStatus,
  'baseCurrency' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'multiCurrencyEnabled' : IDL.Bool,
  'coverImage' : IDL.Text,
  'vendorId' : IDL.Text,
  'category' : EventCategory,
  'eventDate' : Time,
  'supportedCurrencies' : IDL.Vec(IDL.Text),
});
export const TicketType = IDL.Variant({
  'numberedSeat' : IDL.Null,
  'generalAdmission' : IDL.Null,
  'timeSlot' : IDL.Null,
});
export const Ticket = IDL.Record({
  'id' : IDL.Text,
  'eventId' : IDL.Text,
  'baseCurrency' : IDL.Text,
  'availableQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'ticketType' : TicketType,
  'price' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'refunded' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'eventId' : IDL.Text,
  'seatNumbers' : IDL.Vec(IDL.Nat),
  'idempotencyKey' : IDL.Text,
  'ticketTypeId' : IDL.Text,
  'userId' : IDL.Text,
  'fraudScore' : IDL.Nat,
  'createdAt' : Time,
  'lockToken' : IDL.Text,
  'totalAmount' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'stripeSessionId' : IDL.Text,
  'timeSlot' : IDL.Opt(IDL.Text),
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const VendorApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const VendorProfile = IDL.Record({
  'userId' : IDL.Text,
  'createdAt' : Time,
  'businessName' : IDL.Text,
  'approvalStatus' : VendorApprovalStatus,
  'totalRevenue' : IDL.Nat,
});
export const ActionType = IDL.Variant({
  'eventPublished' : IDL.Null,
  'refundInitiated' : IDL.Null,
  'paymentSucceeded' : IDL.Null,
  'adminAction' : IDL.Null,
  'bookingCreated' : IDL.Null,
  'bookingConfirmed' : IDL.Null,
  'userRegistered' : IDL.Null,
  'vendorApproved' : IDL.Null,
  'eventCreated' : IDL.Null,
  'fraudHold' : IDL.Null,
  'bookingCancelled' : IDL.Null,
  'paymentFailed' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'actionType' : ActionType,
  'actorId' : IDL.Text,
  'timestamp' : Time,
  'details' : IDL.Text,
  'targetId' : IDL.Text,
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const AppUserRole = IDL.Variant({
  'customer' : IDL.Null,
  'superAdmin' : IDL.Null,
  'vendor' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Text,
  'status' : UserStatus,
  'appRole' : AppUserRole,
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
});
export const CurrencyConfig = IDL.Record({
  'eventId' : IDL.Text,
  'baseCurrency' : IDL.Text,
  'multiCurrencyEnabled' : IDL.Bool,
  'updatedAt' : Time,
  'supportedCurrencies' : IDL.Vec(IDL.Text),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const RefundStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'processed' : IDL.Null,
});
export const Refund = IDL.Record({
  'id' : IDL.Text,
  'status' : RefundStatus,
  'bookingId' : IDL.Text,
  'createdAt' : Time,
  'amount' : IDL.Nat,
  'reason' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateEventArgs = IDL.Record({
  'id' : IDL.Text,
  'status' : EventStatus,
  'baseCurrency' : IDL.Text,
  'title' : IDL.Text,
  'country' : IDL.Text,
  'venue' : IDL.Text,
  'city' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'multiCurrencyEnabled' : IDL.Bool,
  'coverImage' : IDL.Text,
  'vendorId' : IDL.Text,
  'category' : EventCategory,
  'eventDate' : Time,
  'supportedCurrencies' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateUser' : IDL.Func([IDL.Principal], [], []),
  'addEvent' : IDL.Func([AddEventArgs], [Event], []),
  'addTicket' : IDL.Func([Ticket], [Ticket], []),
  'approveVendor' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Text], [], []),
  'createBooking' : IDL.Func([Booking], [Booking], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createVendorProfile' : IDL.Func([IDL.Text], [VendorProfile], []),
  'deleteEvent' : IDL.Func([IDL.Text], [], []),
  'deleteTicket' : IDL.Func([IDL.Text], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
  'getAuditLogs' : IDL.Func(
      [Time, Time, IDL.Opt(ActionType)],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'getBookingById' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrencyConfig' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(CurrencyConfig)],
      ['query'],
    ),
  'getEventById' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
  'getFraudQueue' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getMyVendorEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getMyVendorStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalEvents' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getPlatformStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'confirmedBookings' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalRevenue' : IDL.Nat,
          'totalVendors' : IDL.Nat,
          'activeEvents' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTicketById' : IDL.Func([IDL.Text], [IDL.Opt(Ticket)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVendorApprovalQueue' : IDL.Func([], [IDL.Vec(VendorProfile)], ['query']),
  'getVendorProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VendorProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processRefund' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'rejectVendor' : IDL.Func([IDL.Text], [], []),
  'requestRefund' : IDL.Func([IDL.Text, IDL.Text], [Refund], []),
  'reviewFraudBooking' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setCurrencyConfig' : IDL.Func([CurrencyConfig], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'suspendUser' : IDL.Func([IDL.Principal], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateEvent' : IDL.Func([UpdateEventArgs], [Event], []),
  'updateTicket' : IDL.Func([Ticket], [Ticket], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventCategory = IDL.Variant({
    'concert' : IDL.Null,
    'workshop' : IDL.Null,
    'privateEvent' : IDL.Null,
    'conference' : IDL.Null,
    'sports' : IDL.Null,
  });
  const Time = IDL.Int;
  const AddEventArgs = IDL.Record({
    'id' : IDL.Text,
    'baseCurrency' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'multiCurrencyEnabled' : IDL.Bool,
    'coverImage' : IDL.Text,
    'vendorId' : IDL.Text,
    'category' : EventCategory,
    'eventDate' : Time,
    'supportedCurrencies' : IDL.Vec(IDL.Text),
  });
  const EventStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'published' : IDL.Null,
    'completed' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Text,
    'status' : EventStatus,
    'baseCurrency' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'multiCurrencyEnabled' : IDL.Bool,
    'coverImage' : IDL.Text,
    'vendorId' : IDL.Text,
    'category' : EventCategory,
    'eventDate' : Time,
    'supportedCurrencies' : IDL.Vec(IDL.Text),
  });
  const TicketType = IDL.Variant({
    'numberedSeat' : IDL.Null,
    'generalAdmission' : IDL.Null,
    'timeSlot' : IDL.Null,
  });
  const Ticket = IDL.Record({
    'id' : IDL.Text,
    'eventId' : IDL.Text,
    'baseCurrency' : IDL.Text,
    'availableQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'ticketType' : TicketType,
    'price' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'refunded' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'eventId' : IDL.Text,
    'seatNumbers' : IDL.Vec(IDL.Nat),
    'idempotencyKey' : IDL.Text,
    'ticketTypeId' : IDL.Text,
    'userId' : IDL.Text,
    'fraudScore' : IDL.Nat,
    'createdAt' : Time,
    'lockToken' : IDL.Text,
    'totalAmount' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'stripeSessionId' : IDL.Text,
    'timeSlot' : IDL.Opt(IDL.Text),
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const VendorApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const VendorProfile = IDL.Record({
    'userId' : IDL.Text,
    'createdAt' : Time,
    'businessName' : IDL.Text,
    'approvalStatus' : VendorApprovalStatus,
    'totalRevenue' : IDL.Nat,
  });
  const ActionType = IDL.Variant({
    'eventPublished' : IDL.Null,
    'refundInitiated' : IDL.Null,
    'paymentSucceeded' : IDL.Null,
    'adminAction' : IDL.Null,
    'bookingCreated' : IDL.Null,
    'bookingConfirmed' : IDL.Null,
    'userRegistered' : IDL.Null,
    'vendorApproved' : IDL.Null,
    'eventCreated' : IDL.Null,
    'fraudHold' : IDL.Null,
    'bookingCancelled' : IDL.Null,
    'paymentFailed' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'actionType' : ActionType,
    'actorId' : IDL.Text,
    'timestamp' : Time,
    'details' : IDL.Text,
    'targetId' : IDL.Text,
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const AppUserRole = IDL.Variant({
    'customer' : IDL.Null,
    'superAdmin' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Text,
    'status' : UserStatus,
    'appRole' : AppUserRole,
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
  });
  const CurrencyConfig = IDL.Record({
    'eventId' : IDL.Text,
    'baseCurrency' : IDL.Text,
    'multiCurrencyEnabled' : IDL.Bool,
    'updatedAt' : Time,
    'supportedCurrencies' : IDL.Vec(IDL.Text),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const RefundStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'processed' : IDL.Null,
  });
  const Refund = IDL.Record({
    'id' : IDL.Text,
    'status' : RefundStatus,
    'bookingId' : IDL.Text,
    'createdAt' : Time,
    'amount' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateEventArgs = IDL.Record({
    'id' : IDL.Text,
    'status' : EventStatus,
    'baseCurrency' : IDL.Text,
    'title' : IDL.Text,
    'country' : IDL.Text,
    'venue' : IDL.Text,
    'city' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'multiCurrencyEnabled' : IDL.Bool,
    'coverImage' : IDL.Text,
    'vendorId' : IDL.Text,
    'category' : EventCategory,
    'eventDate' : Time,
    'supportedCurrencies' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateUser' : IDL.Func([IDL.Principal], [], []),
    'addEvent' : IDL.Func([AddEventArgs], [Event], []),
    'addTicket' : IDL.Func([Ticket], [Ticket], []),
    'approveVendor' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Text], [], []),
    'createBooking' : IDL.Func([Booking], [Booking], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createVendorProfile' : IDL.Func([IDL.Text], [VendorProfile], []),
    'deleteEvent' : IDL.Func([IDL.Text], [], []),
    'deleteTicket' : IDL.Func([IDL.Text], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllTickets' : IDL.Func([], [IDL.Vec(Ticket)], ['query']),
    'getAuditLogs' : IDL.Func(
        [Time, Time, IDL.Opt(ActionType)],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getBookingById' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrencyConfig' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CurrencyConfig)],
        ['query'],
      ),
    'getEventById' : IDL.Func([IDL.Text], [IDL.Opt(Event)], ['query']),
    'getFraudQueue' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getMyVendorEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getMyVendorStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalEvents' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getPlatformStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'confirmedBookings' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalRevenue' : IDL.Nat,
            'totalVendors' : IDL.Nat,
            'activeEvents' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTicketById' : IDL.Func([IDL.Text], [IDL.Opt(Ticket)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVendorApprovalQueue' : IDL.Func(
        [],
        [IDL.Vec(VendorProfile)],
        ['query'],
      ),
    'getVendorProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VendorProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processRefund' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'rejectVendor' : IDL.Func([IDL.Text], [], []),
    'requestRefund' : IDL.Func([IDL.Text, IDL.Text], [Refund], []),
    'reviewFraudBooking' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setCurrencyConfig' : IDL.Func([CurrencyConfig], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'suspendUser' : IDL.Func([IDL.Principal], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateEvent' : IDL.Func([UpdateEventArgs], [Event], []),
    'updateTicket' : IDL.Func([Ticket], [Ticket], []),
  });
};

export const init = ({ IDL }) => { return []; };