/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActionType = { 'eventPublished' : null } |
  { 'refundInitiated' : null } |
  { 'paymentSucceeded' : null } |
  { 'adminAction' : null } |
  { 'bookingCreated' : null } |
  { 'bookingConfirmed' : null } |
  { 'userRegistered' : null } |
  { 'vendorApproved' : null } |
  { 'eventCreated' : null } |
  { 'fraudHold' : null } |
  { 'bookingCancelled' : null } |
  { 'paymentFailed' : null };
export interface AddEventArgs {
  'id' : string,
  'baseCurrency' : string,
  'title' : string,
  'country' : string,
  'venue' : string,
  'city' : string,
  'tags' : Array<string>,
  'description' : string,
  'multiCurrencyEnabled' : boolean,
  'coverImage' : string,
  'vendorId' : string,
  'category' : EventCategory,
  'eventDate' : Time,
  'supportedCurrencies' : Array<string>,
}
export type AppUserRole = { 'customer' : null } |
  { 'superAdmin' : null } |
  { 'vendor' : null };
export interface AuditLog {
  'actionType' : ActionType,
  'actorId' : string,
  'timestamp' : Time,
  'details' : string,
  'targetId' : string,
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'eventId' : string,
  'seatNumbers' : Array<bigint>,
  'idempotencyKey' : string,
  'ticketTypeId' : string,
  'userId' : string,
  'fraudScore' : bigint,
  'createdAt' : Time,
  'lockToken' : string,
  'totalAmount' : bigint,
  'notes' : [] | [string],
  'quantity' : bigint,
  'stripeSessionId' : string,
  'timeSlot' : [] | [string],
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'refunded' : null } |
  { 'confirmed' : null };
export interface CurrencyConfig {
  'eventId' : string,
  'baseCurrency' : string,
  'multiCurrencyEnabled' : boolean,
  'updatedAt' : Time,
  'supportedCurrencies' : Array<string>,
}
export interface Event {
  'id' : string,
  'status' : EventStatus,
  'baseCurrency' : string,
  'title' : string,
  'country' : string,
  'venue' : string,
  'city' : string,
  'createdAt' : Time,
  'tags' : Array<string>,
  'description' : string,
  'multiCurrencyEnabled' : boolean,
  'coverImage' : string,
  'vendorId' : string,
  'category' : EventCategory,
  'eventDate' : Time,
  'supportedCurrencies' : Array<string>,
}
export type EventCategory = { 'concert' : null } |
  { 'workshop' : null } |
  { 'privateEvent' : null } |
  { 'conference' : null } |
  { 'sports' : null };
export type EventStatus = { 'cancelled' : null } |
  { 'published' : null } |
  { 'completed' : null } |
  { 'draft' : null };
export interface Refund {
  'id' : string,
  'status' : RefundStatus,
  'bookingId' : string,
  'createdAt' : Time,
  'amount' : bigint,
  'reason' : string,
}
export type RefundStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'processed' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Ticket {
  'id' : string,
  'eventId' : string,
  'baseCurrency' : string,
  'availableQuantity' : bigint,
  'name' : string,
  'ticketType' : TicketType,
  'price' : bigint,
  'totalQuantity' : bigint,
}
export type TicketType = { 'numberedSeat' : null } |
  { 'generalAdmission' : null } |
  { 'timeSlot' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateEventArgs {
  'id' : string,
  'status' : EventStatus,
  'baseCurrency' : string,
  'title' : string,
  'country' : string,
  'venue' : string,
  'city' : string,
  'tags' : Array<string>,
  'description' : string,
  'multiCurrencyEnabled' : boolean,
  'coverImage' : string,
  'vendorId' : string,
  'category' : EventCategory,
  'eventDate' : Time,
  'supportedCurrencies' : Array<string>,
}
export interface UserProfile {
  'id' : string,
  'status' : UserStatus,
  'appRole' : AppUserRole,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserStatus = { 'active' : null } |
  { 'suspended' : null };
export type VendorApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface VendorProfile {
  'userId' : string,
  'createdAt' : Time,
  'businessName' : string,
  'approvalStatus' : VendorApprovalStatus,
  'totalRevenue' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateUser' : ActorMethod<[Principal], undefined>,
  'addEvent' : ActorMethod<[AddEventArgs], Event>,
  'addTicket' : ActorMethod<[Ticket], Ticket>,
  'approveVendor' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<[Booking], Booking>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createVendorProfile' : ActorMethod<[string], VendorProfile>,
  'deleteEvent' : ActorMethod<[string], undefined>,
  'deleteTicket' : ActorMethod<[string], undefined>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllTickets' : ActorMethod<[], Array<Ticket>>,
  'getAuditLogs' : ActorMethod<
    [Time, Time, [] | [ActionType]],
    Array<AuditLog>
  >,
  'getBookingById' : ActorMethod<[string], [] | [Booking]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrencyConfig' : ActorMethod<[string], [] | [CurrencyConfig]>,
  'getEventById' : ActorMethod<[string], [] | [Event]>,
  'getFraudQueue' : ActorMethod<[], Array<Booking>>,
  'getMyBookings' : ActorMethod<[], Array<Booking>>,
  'getMyVendorEvents' : ActorMethod<[], Array<Event>>,
  'getMyVendorStats' : ActorMethod<
    [],
    {
      'totalEvents' : bigint,
      'totalBookings' : bigint,
      'totalRevenue' : bigint,
    }
  >,
  'getPlatformStats' : ActorMethod<
    [],
    {
      'confirmedBookings' : bigint,
      'totalUsers' : bigint,
      'totalRevenue' : bigint,
      'totalVendors' : bigint,
      'activeEvents' : bigint,
    }
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTicketById' : ActorMethod<[string], [] | [Ticket]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVendorApprovalQueue' : ActorMethod<[], Array<VendorProfile>>,
  'getVendorProfile' : ActorMethod<[string], [] | [VendorProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processRefund' : ActorMethod<[string, boolean], undefined>,
  'rejectVendor' : ActorMethod<[string], undefined>,
  'requestRefund' : ActorMethod<[string, string], Refund>,
  'reviewFraudBooking' : ActorMethod<[string, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setCurrencyConfig' : ActorMethod<[CurrencyConfig], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'suspendUser' : ActorMethod<[Principal], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateEvent' : ActorMethod<[UpdateEventArgs], Event>,
  'updateTicket' : ActorMethod<[Ticket], Ticket>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];