/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VotingEntry {
    id: bigint;
    region: string;
    voteCount: bigint;
    createdAt: Time;
    category: string;
    artistName: string;
}
export interface AuditLog {
    id: bigint;
    action: string;
    entityId: string;
    timestamp: bigint;
    details: string;
    entityType: string;
    userActor: Principal;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface User {
    isApproved: boolean;
    principal: Principal;
    name: string;
    createdAt: Time;
    role: UserRole;
    email: string;
}
export interface Event {
    id: bigint;
    baseCurrency: string;
    title: string;
    endDate: Time;
    isPublished: boolean;
    basePriceINR: bigint;
    globalRank?: bigint;
    createdAt: Time;
    tags: Array<string>;
    isTop100India: boolean;
    description: string;
    multiCurrencyEnabled: boolean;
    indiaRank?: bigint;
    totalSeats: bigint;
    updatedAt: Time;
    isTop100Global: boolean;
    ticketType: TicketType;
    availableSeats: bigint;
    vendorId: Principal;
    promoVideoUrl: string;
    bannerUrl: string;
    location: string;
    startDate: Time;
    supportedCurrencies: Array<string>;
    eventType: EventType;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ExchangeRates {
    inrToAed: number;
    inrToEur: number;
    inrToGbp: number;
    inrToUsd: number;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface AIItineraryLog {
    id: bigint;
    status: AIItineraryStatus;
    eventId?: string;
    destination: string;
    userId: Principal;
    createdAt: Time;
    travelDates: string;
    itineraryData: string;
    services: Array<string>;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface PreloadedEventProfile {
    id: bigint;
    eventId?: string;
    title: string;
    basePriceINR: bigint;
    globalRank?: bigint;
    isTop100India: boolean;
    indiaRank?: bigint;
    isActive: boolean;
    isTop100Global: boolean;
    promoVideoUrl: string;
    bannerUrl: string;
    location: string;
    eventType: EventType;
}
export interface FraudLog {
    id: bigint;
    flags: Array<string>;
    status: FraudStatus;
    bookingId: bigint;
    userId: Principal;
    createdAt: Time;
    riskScore: bigint;
}
export interface EscrowPayout {
    id: bigint;
    status: EscrowPayoutStatus;
    eventId: bigint;
    processedAt?: bigint;
    adminNote?: string;
    vendorId: Principal;
    amountINR: bigint;
    requestedAt: bigint;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    eventId: bigint;
    userId: Principal;
    createdAt: Time;
    confirmedAt?: bigint;
    cancelledAt?: bigint;
    ticketType: TicketType;
    totalAmountINR: bigint;
    currency: string;
    quantity: bigint;
    seatLockId: bigint;
    bookingToken: string;
    stripeSessionId?: string;
}
export enum AIItineraryStatus {
    cancelled = "cancelled",
    confirmed = "confirmed",
    draft = "draft"
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    refunded = "refunded",
    confirmed = "confirmed",
    onHold = "onHold"
}
export enum EscrowPayoutStatus {
    pending = "pending",
    released = "released",
    rejected = "rejected"
}
export enum EventType {
    dj = "dj",
    workshop = "workshop",
    modelingAssignment = "modelingAssignment",
    musicFestival = "musicFestival",
    privateEvent = "privateEvent",
    conference = "conference",
    luxuryParty = "luxuryParty",
    sports = "sports",
    celebrity = "celebrity"
}
export enum FraudStatus {
    autoHeld = "autoHeld",
    cleared = "cleared",
    flagged = "flagged"
}
export enum TicketType {
    numberedSeat = "numberedSeat",
    vipPackage = "vipPackage",
    generalAdmission = "generalAdmission",
    timeSlot = "timeSlot"
}
export enum UserRole {
    admin = "admin",
    customer = "customer",
    superAdmin = "superAdmin",
    vendor = "vendor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveVendor(vendorPrincipal: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    cancelBooking(bookingId: bigint): Promise<void>;
    confirmBooking(bookingId: bigint, stripeSessionId: string): Promise<void>;
    createBooking(eventId: bigint, seatLockId: bigint, quantity: bigint, currency: string): Promise<bigint>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createEvent(title: string, description: string, eventType: EventType, location: string, startDate: Time, endDate: Time, basePriceINR: bigint, supportedCurrencies: Array<string>, multiCurrencyEnabled: boolean, totalSeats: bigint, ticketType: TicketType, bannerUrl: string, promoVideoUrl: string, tags: Array<string>): Promise<bigint>;
    createItinerary(eventId: string | null, destination: string, travelDates: string, services: Array<string>): Promise<bigint>;
    createPreloadedProfile(eventId: string | null, title: string, eventType: EventType, location: string, basePriceINR: bigint, bannerUrl: string, promoVideoUrl: string, isTop100Global: boolean, isTop100India: boolean, globalRank: bigint | null, indiaRank: bigint | null): Promise<bigint>;
    deleteEvent(eventId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<User | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getEvent(eventId: bigint): Promise<Event | null>;
    getExchangeRates(): Promise<ExchangeRates>;
    getItinerary(itineraryId: bigint): Promise<AIItineraryLog | null>;
    getLeaderboard(region: string | null, category: string | null, limit: bigint): Promise<Array<VotingEntry>>;
    getPlatformStats(): Promise<{
        totalRevenueINR: bigint;
        totalEvents: bigint;
        totalBookings: bigint;
        pendingEscrowPayouts: bigint;
        totalUsers: bigint;
        activeFraudAlerts: bigint;
        totalVendors: bigint;
    }>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<User | null>;
    getVendorStats(): Promise<{
        bookingsCount: bigint;
        revenueINR: bigint;
        eventsCount: bigint;
    }>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllBookings(): Promise<Array<Booking>>;
    listAllUsers(): Promise<Array<User>>;
    listAuditLogs(userActor: Principal | null, action: string | null, startTime: bigint | null, endTime: bigint | null): Promise<Array<AuditLog>>;
    listEscrowPayouts(): Promise<Array<EscrowPayout>>;
    listFraudLogs(): Promise<Array<FraudLog>>;
    listMyBookings(): Promise<Array<Booking>>;
    listMyItineraries(): Promise<Array<AIItineraryLog>>;
    listPreloadedProfiles(): Promise<Array<PreloadedEventProfile>>;
    listPublishedEvents(eventType: EventType | null, location: string | null, minPrice: bigint | null, maxPrice: bigint | null, isTop100Global: boolean | null, isTop100India: boolean | null): Promise<Array<Event>>;
    lockSeat(eventId: bigint, seatNumber: string | null): Promise<string>;
    publishEvent(eventId: bigint): Promise<void>;
    registerUser(name: string, email: string, role: UserRole): Promise<void>;
    rejectEscrowPayout(payoutId: bigint, adminNote: string): Promise<void>;
    releaseEscrowPayout(payoutId: bigint, adminNote: string): Promise<void>;
    requestEscrowPayout(eventId: bigint): Promise<bigint>;
    reviewFraudFlag(fraudLogId: bigint, clearFlag: boolean): Promise<void>;
    saveCallerUserProfile(name: string, email: string): Promise<void>;
    setEventTop100(eventId: bigint, isTop100Global: boolean, isTop100India: boolean, globalRank: bigint | null, indiaRank: bigint | null): Promise<void>;
    setExchangeRates(inrToUsd: number, inrToEur: number, inrToAed: number, inrToGbp: number): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    unpublishEvent(eventId: bigint): Promise<void>;
    updateEvent(eventId: bigint, title: string, description: string, location: string, basePriceINR: bigint, bannerUrl: string, promoVideoUrl: string, tags: Array<string>): Promise<void>;
    voteForArtist(artistName: string, category: string, region: string): Promise<void>;
}
import type { AIItineraryLog as _AIItineraryLog, AIItineraryStatus as _AIItineraryStatus, Booking as _Booking, BookingStatus as _BookingStatus, EscrowPayout as _EscrowPayout, EscrowPayoutStatus as _EscrowPayoutStatus, Event as _Event, EventType as _EventType, FraudLog as _FraudLog, FraudStatus as _FraudStatus, PreloadedEventProfile as _PreloadedEventProfile, StripeSessionStatus as _StripeSessionStatus, TicketType as _TicketType, Time as _Time, User as _User, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveVendor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveVendor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async confirmBooking(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmBooking(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: bigint, arg2: bigint, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createEvent(arg0: string, arg1: string, arg2: EventType, arg3: string, arg4: Time, arg5: Time, arg6: bigint, arg7: Array<string>, arg8: boolean, arg9: bigint, arg10: TicketType, arg11: string, arg12: string, arg13: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(arg0, arg1, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_TicketType_n5(this._uploadFile, this._downloadFile, arg10), arg11, arg12, arg13);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(arg0, arg1, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_TicketType_n5(this._uploadFile, this._downloadFile, arg10), arg11, arg12, arg13);
            return result;
        }
    }
    async createItinerary(arg0: string | null, arg1: string, arg2: string, arg3: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createItinerary(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createItinerary(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3);
            return result;
        }
    }
    async createPreloadedProfile(arg0: string | null, arg1: string, arg2: EventType, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: boolean, arg8: boolean, arg9: bigint | null, arg10: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createPreloadedProfile(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg10));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPreloadedProfile(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_EventType_n3(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg9), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg10));
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEvent(arg0: bigint): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEvent(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEvent(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExchangeRates(): Promise<ExchangeRates> {
        if (this.processError) {
            try {
                const result = await this.actor.getExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExchangeRates();
            return result;
        }
    }
    async getItinerary(arg0: bigint): Promise<AIItineraryLog | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItinerary(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItinerary(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeaderboard(arg0: string | null, arg1: string | null, arg2: bigint): Promise<Array<VotingEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async getPlatformStats(): Promise<{
        totalRevenueINR: bigint;
        totalEvents: bigint;
        totalBookings: bigint;
        pendingEscrowPayouts: bigint;
        totalUsers: bigint;
        activeFraudAlerts: bigint;
        totalVendors: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorStats(): Promise<{
        bookingsCount: bigint;
        revenueINR: bigint;
        eventsCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorStats();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllBookings();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllBookings();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAuditLogs(arg0: Principal | null, arg1: string | null, arg2: bigint | null, arg3: bigint | null): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAuditLogs(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAuditLogs(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async listEscrowPayouts(): Promise<Array<EscrowPayout>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEscrowPayouts();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEscrowPayouts();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async listFraudLogs(): Promise<Array<FraudLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFraudLogs();
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFraudLogs();
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyBookings();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyBookings();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async listMyItineraries(): Promise<Array<AIItineraryLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyItineraries();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyItineraries();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPreloadedProfiles(): Promise<Array<PreloadedEventProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPreloadedProfiles();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPreloadedProfiles();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPublishedEvents(arg0: EventType | null, arg1: string | null, arg2: bigint | null, arg3: bigint | null, arg4: boolean | null, arg5: boolean | null): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPublishedEvents(to_candid_opt_n56(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg5));
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPublishedEvents(to_candid_opt_n56(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n57(this._uploadFile, this._downloadFile, arg5));
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async lockSeat(arg0: bigint, arg1: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.lockSeat(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lockSeat(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async publishEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.publishEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishEvent(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_UserRole_n59(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_UserRole_n59(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async rejectEscrowPayout(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectEscrowPayout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectEscrowPayout(arg0, arg1);
            return result;
        }
    }
    async releaseEscrowPayout(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.releaseEscrowPayout(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.releaseEscrowPayout(arg0, arg1);
            return result;
        }
    }
    async requestEscrowPayout(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestEscrowPayout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestEscrowPayout(arg0);
            return result;
        }
    }
    async reviewFraudFlag(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewFraudFlag(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewFraudFlag(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1);
            return result;
        }
    }
    async setEventTop100(arg0: bigint, arg1: boolean, arg2: boolean, arg3: bigint | null, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEventTop100(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEventTop100(arg0, arg1, arg2, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async setExchangeRates(arg0: number, arg1: number, arg2: number, arg3: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setExchangeRates(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setExchangeRates(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async unpublishEvent(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishEvent(arg0);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: string, arg6: string, arg7: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async voteForArtist(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.voteForArtist(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.voteForArtist(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AIItineraryLog_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIItineraryLog): AIItineraryLog {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_AIItineraryStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AIItineraryStatus): AIItineraryStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_EscrowPayoutStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscrowPayoutStatus): EscrowPayoutStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_EscrowPayout_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EscrowPayout): EscrowPayout {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_EventType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventType): EventType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_FraudLog_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FraudLog): FraudLog {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_FraudStatus_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FraudStatus): FraudStatus {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_PreloadedEventProfile_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PreloadedEventProfile): PreloadedEventProfile {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_TicketType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketType): TicketType {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_User_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : from_candid_Event_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AIItineraryLog]): AIItineraryLog | null {
    return value.length === 0 ? null : from_candid_AIItineraryLog_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isApproved: boolean;
    principal: Principal;
    name: string;
    createdAt: _Time;
    role: _UserRole;
    email: string;
}): {
    isApproved: boolean;
    principal: Principal;
    name: string;
    createdAt: Time;
    role: UserRole;
    email: string;
} {
    return {
        isApproved: value.isApproved,
        principal: value.principal,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n12(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    baseCurrency: string;
    title: string;
    endDate: _Time;
    isPublished: boolean;
    basePriceINR: bigint;
    globalRank: [] | [bigint];
    createdAt: _Time;
    tags: Array<string>;
    isTop100India: boolean;
    description: string;
    multiCurrencyEnabled: boolean;
    indiaRank: [] | [bigint];
    totalSeats: bigint;
    updatedAt: _Time;
    isTop100Global: boolean;
    ticketType: _TicketType;
    availableSeats: bigint;
    vendorId: Principal;
    promoVideoUrl: string;
    bannerUrl: string;
    location: string;
    startDate: _Time;
    supportedCurrencies: Array<string>;
    eventType: _EventType;
}): {
    id: bigint;
    baseCurrency: string;
    title: string;
    endDate: Time;
    isPublished: boolean;
    basePriceINR: bigint;
    globalRank?: bigint;
    createdAt: Time;
    tags: Array<string>;
    isTop100India: boolean;
    description: string;
    multiCurrencyEnabled: boolean;
    indiaRank?: bigint;
    totalSeats: bigint;
    updatedAt: Time;
    isTop100Global: boolean;
    ticketType: TicketType;
    availableSeats: bigint;
    vendorId: Principal;
    promoVideoUrl: string;
    bannerUrl: string;
    location: string;
    startDate: Time;
    supportedCurrencies: Array<string>;
    eventType: EventType;
} {
    return {
        id: value.id,
        baseCurrency: value.baseCurrency,
        title: value.title,
        endDate: value.endDate,
        isPublished: value.isPublished,
        basePriceINR: value.basePriceINR,
        globalRank: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.globalRank)),
        createdAt: value.createdAt,
        tags: value.tags,
        isTop100India: value.isTop100India,
        description: value.description,
        multiCurrencyEnabled: value.multiCurrencyEnabled,
        indiaRank: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.indiaRank)),
        totalSeats: value.totalSeats,
        updatedAt: value.updatedAt,
        isTop100Global: value.isTop100Global,
        ticketType: from_candid_TicketType_n20(_uploadFile, _downloadFile, value.ticketType),
        availableSeats: value.availableSeats,
        vendorId: value.vendorId,
        promoVideoUrl: value.promoVideoUrl,
        bannerUrl: value.bannerUrl,
        location: value.location,
        startDate: value.startDate,
        supportedCurrencies: value.supportedCurrencies,
        eventType: from_candid_EventType_n22(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AIItineraryStatus;
    eventId: [] | [string];
    destination: string;
    userId: Principal;
    createdAt: _Time;
    travelDates: string;
    itineraryData: string;
    services: Array<string>;
}): {
    id: bigint;
    status: AIItineraryStatus;
    eventId?: string;
    destination: string;
    userId: Principal;
    createdAt: Time;
    travelDates: string;
    itineraryData: string;
    services: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_AIItineraryStatus_n27(_uploadFile, _downloadFile, value.status),
        eventId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.eventId)),
        destination: value.destination,
        userId: value.userId,
        createdAt: value.createdAt,
        travelDates: value.travelDates,
        itineraryData: value.itineraryData,
        services: value.services
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    eventId: bigint;
    userId: Principal;
    createdAt: _Time;
    confirmedAt: [] | [bigint];
    cancelledAt: [] | [bigint];
    ticketType: _TicketType;
    totalAmountINR: bigint;
    currency: string;
    quantity: bigint;
    seatLockId: bigint;
    bookingToken: string;
    stripeSessionId: [] | [string];
}): {
    id: bigint;
    status: BookingStatus;
    eventId: bigint;
    userId: Principal;
    createdAt: Time;
    confirmedAt?: bigint;
    cancelledAt?: bigint;
    ticketType: TicketType;
    totalAmountINR: bigint;
    currency: string;
    quantity: bigint;
    seatLockId: bigint;
    bookingToken: string;
    stripeSessionId?: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n36(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        userId: value.userId,
        createdAt: value.createdAt,
        confirmedAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.confirmedAt)),
        cancelledAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.cancelledAt)),
        ticketType: from_candid_TicketType_n20(_uploadFile, _downloadFile, value.ticketType),
        totalAmountINR: value.totalAmountINR,
        currency: value.currency,
        quantity: value.quantity,
        seatLockId: value.seatLockId,
        bookingToken: value.bookingToken,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.stripeSessionId))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _EscrowPayoutStatus;
    eventId: bigint;
    processedAt: [] | [bigint];
    adminNote: [] | [string];
    vendorId: Principal;
    amountINR: bigint;
    requestedAt: bigint;
}): {
    id: bigint;
    status: EscrowPayoutStatus;
    eventId: bigint;
    processedAt?: bigint;
    adminNote?: string;
    vendorId: Principal;
    amountINR: bigint;
    requestedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_EscrowPayoutStatus_n45(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        processedAt: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.processedAt)),
        adminNote: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.adminNote)),
        vendorId: value.vendorId,
        amountINR: value.amountINR,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    flags: Array<string>;
    status: _FraudStatus;
    bookingId: bigint;
    userId: Principal;
    createdAt: _Time;
    riskScore: bigint;
}): {
    id: bigint;
    flags: Array<string>;
    status: FraudStatus;
    bookingId: bigint;
    userId: Principal;
    createdAt: Time;
    riskScore: bigint;
} {
    return {
        id: value.id,
        flags: value.flags,
        status: from_candid_FraudStatus_n50(_uploadFile, _downloadFile, value.status),
        bookingId: value.bookingId,
        userId: value.userId,
        createdAt: value.createdAt,
        riskScore: value.riskScore
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    eventId: [] | [string];
    title: string;
    basePriceINR: bigint;
    globalRank: [] | [bigint];
    isTop100India: boolean;
    indiaRank: [] | [bigint];
    isActive: boolean;
    isTop100Global: boolean;
    promoVideoUrl: string;
    bannerUrl: string;
    location: string;
    eventType: _EventType;
}): {
    id: bigint;
    eventId?: string;
    title: string;
    basePriceINR: bigint;
    globalRank?: bigint;
    isTop100India: boolean;
    indiaRank?: bigint;
    isActive: boolean;
    isTop100Global: boolean;
    promoVideoUrl: string;
    bannerUrl: string;
    location: string;
    eventType: EventType;
} {
    return {
        id: value.id,
        eventId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.eventId)),
        title: value.title,
        basePriceINR: value.basePriceINR,
        globalRank: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.globalRank)),
        isTop100India: value.isTop100India,
        indiaRank: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.indiaRank)),
        isActive: value.isActive,
        isTop100Global: value.isTop100Global,
        promoVideoUrl: value.promoVideoUrl,
        bannerUrl: value.bannerUrl,
        location: value.location,
        eventType: from_candid_EventType_n22(_uploadFile, _downloadFile, value.eventType)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    customer: null;
} | {
    superAdmin: null;
} | {
    vendor: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "customer" in value ? UserRole.customer : "superAdmin" in value ? UserRole.superAdmin : "vendor" in value ? UserRole.vendor : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    numberedSeat: null;
} | {
    vipPackage: null;
} | {
    generalAdmission: null;
} | {
    timeSlot: null;
}): TicketType {
    return "numberedSeat" in value ? TicketType.numberedSeat : "vipPackage" in value ? TicketType.vipPackage : "generalAdmission" in value ? TicketType.generalAdmission : "timeSlot" in value ? TicketType.timeSlot : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dj: null;
} | {
    workshop: null;
} | {
    modelingAssignment: null;
} | {
    musicFestival: null;
} | {
    privateEvent: null;
} | {
    conference: null;
} | {
    luxuryParty: null;
} | {
    sports: null;
} | {
    celebrity: null;
}): EventType {
    return "dj" in value ? EventType.dj : "workshop" in value ? EventType.workshop : "modelingAssignment" in value ? EventType.modelingAssignment : "musicFestival" in value ? EventType.musicFestival : "privateEvent" in value ? EventType.privateEvent : "conference" in value ? EventType.conference : "luxuryParty" in value ? EventType.luxuryParty : "sports" in value ? EventType.sports : "celebrity" in value ? EventType.celebrity : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    confirmed: null;
} | {
    draft: null;
}): AIItineraryStatus {
    return "cancelled" in value ? AIItineraryStatus.cancelled : "confirmed" in value ? AIItineraryStatus.confirmed : "draft" in value ? AIItineraryStatus.draft : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n32(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    refunded: null;
} | {
    confirmed: null;
} | {
    onHold: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "refunded" in value ? BookingStatus.refunded : "confirmed" in value ? BookingStatus.confirmed : "onHold" in value ? BookingStatus.onHold : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    released: null;
} | {
    rejected: null;
}): EscrowPayoutStatus {
    return "pending" in value ? EscrowPayoutStatus.pending : "released" in value ? EscrowPayoutStatus.released : "rejected" in value ? EscrowPayoutStatus.rejected : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autoHeld: null;
} | {
    cleared: null;
} | {
    flagged: null;
}): FraudStatus {
    return "autoHeld" in value ? FraudStatus.autoHeld : "cleared" in value ? FraudStatus.cleared : "flagged" in value ? FraudStatus.flagged : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EscrowPayout>): Array<EscrowPayout> {
    return value.map((x)=>from_candid_EscrowPayout_n43(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FraudLog>): Array<FraudLog> {
    return value.map((x)=>from_candid_FraudLog_n48(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AIItineraryLog>): Array<AIItineraryLog> {
    return value.map((x)=>from_candid_AIItineraryLog_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PreloadedEventProfile>): Array<PreloadedEventProfile> {
    return value.map((x)=>from_candid_PreloadedEventProfile_n54(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n17(_uploadFile, _downloadFile, x));
}
function to_candid_EventType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): _EventType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TicketType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): _TicketType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Principal | null): [] | [Principal] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType | null): [] | [_EventType] {
    return value === null ? candid_none() : candid_some(to_candid_EventType_n3(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: boolean | null): [] | [boolean] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventType): {
    dj: null;
} | {
    workshop: null;
} | {
    modelingAssignment: null;
} | {
    musicFestival: null;
} | {
    privateEvent: null;
} | {
    conference: null;
} | {
    luxuryParty: null;
} | {
    sports: null;
} | {
    celebrity: null;
} {
    return value == EventType.dj ? {
        dj: null
    } : value == EventType.workshop ? {
        workshop: null
    } : value == EventType.modelingAssignment ? {
        modelingAssignment: null
    } : value == EventType.musicFestival ? {
        musicFestival: null
    } : value == EventType.privateEvent ? {
        privateEvent: null
    } : value == EventType.conference ? {
        conference: null
    } : value == EventType.luxuryParty ? {
        luxuryParty: null
    } : value == EventType.sports ? {
        sports: null
    } : value == EventType.celebrity ? {
        celebrity: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): {
    numberedSeat: null;
} | {
    vipPackage: null;
} | {
    generalAdmission: null;
} | {
    timeSlot: null;
} {
    return value == TicketType.numberedSeat ? {
        numberedSeat: null
    } : value == TicketType.vipPackage ? {
        vipPackage: null
    } : value == TicketType.generalAdmission ? {
        generalAdmission: null
    } : value == TicketType.timeSlot ? {
        timeSlot: null
    } : value;
}
function to_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    customer: null;
} | {
    superAdmin: null;
} | {
    vendor: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.customer ? {
        customer: null
    } : value == UserRole.superAdmin ? {
        superAdmin: null
    } : value == UserRole.vendor ? {
        vendor: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
