/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AuditLog {
    actionType: ActionType;
    actorId: string;
    timestamp: Time;
    details: string;
    targetId: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface Refund {
    id: string;
    status: RefundStatus;
    bookingId: string;
    createdAt: Time;
    amount: bigint;
    reason: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Booking {
    id: string;
    status: BookingStatus;
    eventId: string;
    seatNumbers: Array<bigint>;
    idempotencyKey: string;
    ticketTypeId: string;
    userId: string;
    fraudScore: bigint;
    createdAt: Time;
    lockToken: string;
    totalAmount: bigint;
    notes?: string;
    quantity: bigint;
    stripeSessionId: string;
    timeSlot?: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface AddEventArgs {
    id: string;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: EventCategory;
    eventDate: Time;
    supportedCurrencies: Array<string>;
}
export interface CurrencyConfig {
    eventId: string;
    baseCurrency: string;
    multiCurrencyEnabled: boolean;
    updatedAt: Time;
    supportedCurrencies: Array<string>;
}
export interface Event {
    id: string;
    status: EventStatus;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    createdAt: Time;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: EventCategory;
    eventDate: Time;
    supportedCurrencies: Array<string>;
}
export interface UpdateEventArgs {
    id: string;
    status: EventStatus;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: EventCategory;
    eventDate: Time;
    supportedCurrencies: Array<string>;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface Ticket {
    id: string;
    eventId: string;
    baseCurrency: string;
    availableQuantity: bigint;
    name: string;
    ticketType: TicketType;
    price: bigint;
    totalQuantity: bigint;
}
export interface VendorProfile {
    userId: string;
    createdAt: Time;
    businessName: string;
    approvalStatus: VendorApprovalStatus;
    totalRevenue: bigint;
}
export interface UserProfile {
    id: string;
    status: UserStatus;
    appRole: AppUserRole;
    name: string;
    createdAt: Time;
    email: string;
}
export enum ActionType {
    eventPublished = "eventPublished",
    refundInitiated = "refundInitiated",
    paymentSucceeded = "paymentSucceeded",
    adminAction = "adminAction",
    bookingCreated = "bookingCreated",
    bookingConfirmed = "bookingConfirmed",
    userRegistered = "userRegistered",
    vendorApproved = "vendorApproved",
    eventCreated = "eventCreated",
    fraudHold = "fraudHold",
    bookingCancelled = "bookingCancelled",
    paymentFailed = "paymentFailed"
}
export enum AppUserRole {
    customer = "customer",
    superAdmin = "superAdmin",
    vendor = "vendor"
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    refunded = "refunded",
    confirmed = "confirmed"
}
export enum EventCategory {
    concert = "concert",
    workshop = "workshop",
    privateEvent = "privateEvent",
    conference = "conference",
    sports = "sports"
}
export enum EventStatus {
    cancelled = "cancelled",
    published = "published",
    completed = "completed",
    draft = "draft"
}
export enum RefundStatus {
    pending = "pending",
    rejected = "rejected",
    processed = "processed"
}
export enum TicketType {
    numberedSeat = "numberedSeat",
    generalAdmission = "generalAdmission",
    timeSlot = "timeSlot"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserStatus {
    active = "active",
    suspended = "suspended"
}
export enum VendorApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateUser(userId: Principal): Promise<void>;
    addEvent(args: AddEventArgs): Promise<Event>;
    addTicket(ticket: Ticket): Promise<Ticket>;
    approveVendor(vendorId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(bookingId: string): Promise<void>;
    createBooking(booking: Booking): Promise<Booking>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createVendorProfile(businessName: string): Promise<VendorProfile>;
    deleteEvent(eventId: string): Promise<void>;
    deleteTicket(ticketId: string): Promise<void>;
    getAllEvents(): Promise<Array<Event>>;
    getAllTickets(): Promise<Array<Ticket>>;
    getAuditLogs(startTime: Time, endTime: Time, actionType: ActionType | null): Promise<Array<AuditLog>>;
    getBookingById(bookingId: string): Promise<Booking | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrencyConfig(eventId: string): Promise<CurrencyConfig | null>;
    getEventById(eventId: string): Promise<Event | null>;
    getFraudQueue(): Promise<Array<Booking>>;
    getMyBookings(): Promise<Array<Booking>>;
    getMyVendorEvents(): Promise<Array<Event>>;
    getMyVendorStats(): Promise<{
        totalEvents: bigint;
        totalBookings: bigint;
        totalRevenue: bigint;
    }>;
    getPlatformStats(): Promise<{
        confirmedBookings: bigint;
        totalUsers: bigint;
        totalRevenue: bigint;
        totalVendors: bigint;
        activeEvents: bigint;
    }>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTicketById(ticketId: string): Promise<Ticket | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVendorApprovalQueue(): Promise<Array<VendorProfile>>;
    getVendorProfile(vendorId: string): Promise<VendorProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    processRefund(refundId: string, approve: boolean): Promise<void>;
    rejectVendor(vendorId: string): Promise<void>;
    requestRefund(bookingId: string, reason: string): Promise<Refund>;
    reviewFraudBooking(bookingId: string, approve: boolean): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setCurrencyConfig(config: CurrencyConfig): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    suspendUser(userId: Principal): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateEvent(args: UpdateEventArgs): Promise<Event>;
    updateTicket(ticket: Ticket): Promise<Ticket>;
}
import type { ActionType as _ActionType, AddEventArgs as _AddEventArgs, AppUserRole as _AppUserRole, AuditLog as _AuditLog, Booking as _Booking, BookingStatus as _BookingStatus, CurrencyConfig as _CurrencyConfig, Event as _Event, EventCategory as _EventCategory, EventStatus as _EventStatus, Refund as _Refund, RefundStatus as _RefundStatus, StripeSessionStatus as _StripeSessionStatus, Ticket as _Ticket, TicketType as _TicketType, Time as _Time, UpdateEventArgs as _UpdateEventArgs, UserProfile as _UserProfile, UserRole as _UserRole, UserStatus as _UserStatus, VendorApprovalStatus as _VendorApprovalStatus, VendorProfile as _VendorProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUser(arg0);
            return result;
        }
    }
    async addEvent(arg0: AddEventArgs): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(to_candid_AddEventArgs_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Event_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(to_candid_AddEventArgs_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Event_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTicket(arg0: Ticket): Promise<Ticket> {
        if (this.processError) {
            try {
                const result = await this.actor.addTicket(to_candid_Ticket_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Ticket_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTicket(to_candid_Ticket_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Ticket_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveVendor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveVendor(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: Booking): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_Booking_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Booking_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_Booking_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Booking_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createVendorProfile(arg0: string): Promise<VendorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createVendorProfile(arg0);
                return from_candid_VendorProfile_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVendorProfile(arg0);
            return from_candid_VendorProfile_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteTicket(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTicket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTicket(arg0);
            return result;
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTickets(): Promise<Array<Ticket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTickets();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTickets();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLogs(arg0: Time, arg1: Time, arg2: ActionType | null): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(arg0, arg1, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingById(arg0: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingById(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingById(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrencyConfig(arg0: string): Promise<CurrencyConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrencyConfig(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrencyConfig(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEventById(arg0: string): Promise<Event | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventById(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventById(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFraudQueue(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFraudQueue();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFraudQueue();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBookings();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBookings();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVendorEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVendorEvents();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVendorEvents();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVendorStats(): Promise<{
        totalEvents: bigint;
        totalBookings: bigint;
        totalRevenue: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVendorStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVendorStats();
            return result;
        }
    }
    async getPlatformStats(): Promise<{
        confirmedBookings: bigint;
        totalUsers: bigint;
        totalRevenue: bigint;
        totalVendors: bigint;
        activeEvents: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTicketById(arg0: string): Promise<Ticket | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTicketById(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTicketById(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorApprovalQueue(): Promise<Array<VendorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorApprovalQueue();
                return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorApprovalQueue();
            return from_candid_vec_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVendorProfile(arg0: string): Promise<VendorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVendorProfile(arg0);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVendorProfile(arg0);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async processRefund(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.processRefund(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processRefund(arg0, arg1);
            return result;
        }
    }
    async rejectVendor(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectVendor(arg0);
            return result;
        }
    }
    async requestRefund(arg0: string, arg1: string): Promise<Refund> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRefund(arg0, arg1);
                return from_candid_Refund_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRefund(arg0, arg1);
            return from_candid_Refund_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async reviewFraudBooking(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.reviewFraudBooking(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.reviewFraudBooking(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n67(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setCurrencyConfig(arg0: CurrencyConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setCurrencyConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCurrencyConfig(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async suspendUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.suspendUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.suspendUser(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateEvent(arg0: UpdateEventArgs): Promise<Event> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(to_candid_UpdateEventArgs_n73(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Event_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(to_candid_UpdateEventArgs_n73(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Event_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTicket(arg0: Ticket): Promise<Ticket> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTicket(to_candid_Ticket_n11(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Ticket_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTicket(to_candid_Ticket_n11(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Ticket_n15(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActionType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActionType): ActionType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_AppUserRole_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppUserRole): AppUserRole {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLog_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_EventCategory_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventCategory): EventCategory {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_EventStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EventStatus): EventStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Event_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Event {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_RefundStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefundStatus): RefundStatus {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_Refund_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Refund): Refund {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function from_candid_TicketType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TicketType): TicketType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Ticket_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Ticket): Ticket {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_VendorApprovalStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorApprovalStatus): VendorApprovalStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_VendorProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VendorProfile): VendorProfile {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CurrencyConfig]): CurrencyConfig | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Event]): Event | null {
    return value.length === 0 ? null : from_candid_Event_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Ticket]): Ticket | null {
    return value.length === 0 ? null : from_candid_Ticket_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VendorProfile]): VendorProfile | null {
    return value.length === 0 ? null : from_candid_VendorProfile_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    eventId: string;
    baseCurrency: string;
    availableQuantity: bigint;
    name: string;
    ticketType: _TicketType;
    price: bigint;
    totalQuantity: bigint;
}): {
    id: string;
    eventId: string;
    baseCurrency: string;
    availableQuantity: bigint;
    name: string;
    ticketType: TicketType;
    price: bigint;
    totalQuantity: bigint;
} {
    return {
        id: value.id,
        eventId: value.eventId,
        baseCurrency: value.baseCurrency,
        availableQuantity: value.availableQuantity,
        name: value.name,
        ticketType: from_candid_TicketType_n17(_uploadFile, _downloadFile, value.ticketType),
        price: value.price,
        totalQuantity: value.totalQuantity
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    eventId: string;
    seatNumbers: Array<bigint>;
    idempotencyKey: string;
    ticketTypeId: string;
    userId: string;
    fraudScore: bigint;
    createdAt: _Time;
    lockToken: string;
    totalAmount: bigint;
    notes: [] | [string];
    quantity: bigint;
    stripeSessionId: string;
    timeSlot: [] | [string];
}): {
    id: string;
    status: BookingStatus;
    eventId: string;
    seatNumbers: Array<bigint>;
    idempotencyKey: string;
    ticketTypeId: string;
    userId: string;
    fraudScore: bigint;
    createdAt: Time;
    lockToken: string;
    totalAmount: bigint;
    notes?: string;
    quantity: bigint;
    stripeSessionId: string;
    timeSlot?: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n27(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        seatNumbers: value.seatNumbers,
        idempotencyKey: value.idempotencyKey,
        ticketTypeId: value.ticketTypeId,
        userId: value.userId,
        fraudScore: value.fraudScore,
        createdAt: value.createdAt,
        lockToken: value.lockToken,
        totalAmount: value.totalAmount,
        notes: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.notes)),
        quantity: value.quantity,
        stripeSessionId: value.stripeSessionId,
        timeSlot: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.timeSlot))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: string;
    createdAt: _Time;
    businessName: string;
    approvalStatus: _VendorApprovalStatus;
    totalRevenue: bigint;
}): {
    userId: string;
    createdAt: Time;
    businessName: string;
    approvalStatus: VendorApprovalStatus;
    totalRevenue: bigint;
} {
    return {
        userId: value.userId,
        createdAt: value.createdAt,
        businessName: value.businessName,
        approvalStatus: from_candid_VendorApprovalStatus_n32(_uploadFile, _downloadFile, value.approvalStatus),
        totalRevenue: value.totalRevenue
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    actionType: _ActionType;
    actorId: string;
    timestamp: _Time;
    details: string;
    targetId: string;
}): {
    actionType: ActionType;
    actorId: string;
    timestamp: Time;
    details: string;
    targetId: string;
} {
    return {
        actionType: from_candid_ActionType_n42(_uploadFile, _downloadFile, value.actionType),
        actorId: value.actorId,
        timestamp: value.timestamp,
        details: value.details,
        targetId: value.targetId
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _UserStatus;
    appRole: _AppUserRole;
    name: string;
    createdAt: _Time;
    email: string;
}): {
    id: string;
    status: UserStatus;
    appRole: AppUserRole;
    name: string;
    createdAt: Time;
    email: string;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n48(_uploadFile, _downloadFile, value.status),
        appRole: from_candid_AppUserRole_n50(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _EventStatus;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    createdAt: _Time;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: _EventCategory;
    eventDate: _Time;
    supportedCurrencies: Array<string>;
}): {
    id: string;
    status: EventStatus;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    createdAt: Time;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: EventCategory;
    eventDate: Time;
    supportedCurrencies: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_EventStatus_n7(_uploadFile, _downloadFile, value.status),
        baseCurrency: value.baseCurrency,
        title: value.title,
        country: value.country,
        venue: value.venue,
        city: value.city,
        createdAt: value.createdAt,
        tags: value.tags,
        description: value.description,
        multiCurrencyEnabled: value.multiCurrencyEnabled,
        coverImage: value.coverImage,
        vendorId: value.vendorId,
        category: from_candid_EventCategory_n9(_uploadFile, _downloadFile, value.category),
        eventDate: value.eventDate,
        supportedCurrencies: value.supportedCurrencies
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _RefundStatus;
    bookingId: string;
    createdAt: _Time;
    amount: bigint;
    reason: string;
}): {
    id: string;
    status: RefundStatus;
    bookingId: string;
    createdAt: Time;
    amount: bigint;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_RefundStatus_n65(_uploadFile, _downloadFile, value.status),
        bookingId: value.bookingId,
        createdAt: value.createdAt,
        amount: value.amount,
        reason: value.reason
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    concert: null;
} | {
    workshop: null;
} | {
    privateEvent: null;
} | {
    conference: null;
} | {
    sports: null;
}): EventCategory {
    return "concert" in value ? EventCategory.concert : "workshop" in value ? EventCategory.workshop : "privateEvent" in value ? EventCategory.privateEvent : "conference" in value ? EventCategory.conference : "sports" in value ? EventCategory.sports : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    numberedSeat: null;
} | {
    generalAdmission: null;
} | {
    timeSlot: null;
}): TicketType {
    return "numberedSeat" in value ? TicketType.numberedSeat : "generalAdmission" in value ? TicketType.generalAdmission : "timeSlot" in value ? TicketType.timeSlot : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    refunded: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "refunded" in value ? BookingStatus.refunded : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): VendorApprovalStatus {
    return "pending" in value ? VendorApprovalStatus.pending : "approved" in value ? VendorApprovalStatus.approved : "rejected" in value ? VendorApprovalStatus.rejected : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eventPublished: null;
} | {
    refundInitiated: null;
} | {
    paymentSucceeded: null;
} | {
    adminAction: null;
} | {
    bookingCreated: null;
} | {
    bookingConfirmed: null;
} | {
    userRegistered: null;
} | {
    vendorApproved: null;
} | {
    eventCreated: null;
} | {
    fraudHold: null;
} | {
    bookingCancelled: null;
} | {
    paymentFailed: null;
}): ActionType {
    return "eventPublished" in value ? ActionType.eventPublished : "refundInitiated" in value ? ActionType.refundInitiated : "paymentSucceeded" in value ? ActionType.paymentSucceeded : "adminAction" in value ? ActionType.adminAction : "bookingCreated" in value ? ActionType.bookingCreated : "bookingConfirmed" in value ? ActionType.bookingConfirmed : "userRegistered" in value ? ActionType.userRegistered : "vendorApproved" in value ? ActionType.vendorApproved : "eventCreated" in value ? ActionType.eventCreated : "fraudHold" in value ? ActionType.fraudHold : "bookingCancelled" in value ? ActionType.bookingCancelled : "paymentFailed" in value ? ActionType.paymentFailed : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    suspended: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "suspended" in value ? UserStatus.suspended : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    superAdmin: null;
} | {
    vendor: null;
}): AppUserRole {
    return "customer" in value ? AppUserRole.customer : "superAdmin" in value ? AppUserRole.superAdmin : "vendor" in value ? AppUserRole.vendor : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n59(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    processed: null;
}): RefundStatus {
    return "pending" in value ? RefundStatus.pending : "rejected" in value ? RefundStatus.rejected : "processed" in value ? RefundStatus.processed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    published: null;
} | {
    completed: null;
} | {
    draft: null;
}): EventStatus {
    return "cancelled" in value ? EventStatus.cancelled : "published" in value ? EventStatus.published : "completed" in value ? EventStatus.completed : "draft" in value ? EventStatus.draft : value;
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Array<Event> {
    return value.map((x)=>from_candid_Event_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Ticket>): Array<Ticket> {
    return value.map((x)=>from_candid_Ticket_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VendorProfile>): Array<VendorProfile> {
    return value.map((x)=>from_candid_VendorProfile_n30(_uploadFile, _downloadFile, x));
}
function to_candid_ActionType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActionType): _ActionType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_AddEventArgs_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddEventArgs): _AddEventArgs {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_AppUserRole_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): _AppUserRole {
    return to_candid_variant_n72(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_Booking_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Booking): _Booking {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_EventCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): _EventCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_EventStatus_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): _EventStatus {
    return to_candid_variant_n76(_uploadFile, _downloadFile, value);
}
function to_candid_TicketType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): _TicketType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Ticket_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Ticket): _Ticket {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateEventArgs_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateEventArgs): _UpdateEventArgs {
    return to_candid_record_n74(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActionType | null): [] | [_ActionType] {
    return value === null ? candid_none() : candid_some(to_candid_ActionType_n37(_uploadFile, _downloadFile, value));
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    eventId: string;
    baseCurrency: string;
    availableQuantity: bigint;
    name: string;
    ticketType: TicketType;
    price: bigint;
    totalQuantity: bigint;
}): {
    id: string;
    eventId: string;
    baseCurrency: string;
    availableQuantity: bigint;
    name: string;
    ticketType: _TicketType;
    price: bigint;
    totalQuantity: bigint;
} {
    return {
        id: value.id,
        eventId: value.eventId,
        baseCurrency: value.baseCurrency,
        availableQuantity: value.availableQuantity,
        name: value.name,
        ticketType: to_candid_TicketType_n13(_uploadFile, _downloadFile, value.ticketType),
        price: value.price,
        totalQuantity: value.totalQuantity
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: EventCategory;
    eventDate: Time;
    supportedCurrencies: Array<string>;
}): {
    id: string;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: _EventCategory;
    eventDate: _Time;
    supportedCurrencies: Array<string>;
} {
    return {
        id: value.id,
        baseCurrency: value.baseCurrency,
        title: value.title,
        country: value.country,
        venue: value.venue,
        city: value.city,
        tags: value.tags,
        description: value.description,
        multiCurrencyEnabled: value.multiCurrencyEnabled,
        coverImage: value.coverImage,
        vendorId: value.vendorId,
        category: to_candid_EventCategory_n3(_uploadFile, _downloadFile, value.category),
        eventDate: value.eventDate,
        supportedCurrencies: value.supportedCurrencies
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: BookingStatus;
    eventId: string;
    seatNumbers: Array<bigint>;
    idempotencyKey: string;
    ticketTypeId: string;
    userId: string;
    fraudScore: bigint;
    createdAt: Time;
    lockToken: string;
    totalAmount: bigint;
    notes?: string;
    quantity: bigint;
    stripeSessionId: string;
    timeSlot?: string;
}): {
    id: string;
    status: _BookingStatus;
    eventId: string;
    seatNumbers: Array<bigint>;
    idempotencyKey: string;
    ticketTypeId: string;
    userId: string;
    fraudScore: bigint;
    createdAt: _Time;
    lockToken: string;
    totalAmount: bigint;
    notes: [] | [string];
    quantity: bigint;
    stripeSessionId: string;
    timeSlot: [] | [string];
} {
    return {
        id: value.id,
        status: to_candid_BookingStatus_n23(_uploadFile, _downloadFile, value.status),
        eventId: value.eventId,
        seatNumbers: value.seatNumbers,
        idempotencyKey: value.idempotencyKey,
        ticketTypeId: value.ticketTypeId,
        userId: value.userId,
        fraudScore: value.fraudScore,
        createdAt: value.createdAt,
        lockToken: value.lockToken,
        totalAmount: value.totalAmount,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        quantity: value.quantity,
        stripeSessionId: value.stripeSessionId,
        timeSlot: value.timeSlot ? candid_some(value.timeSlot) : candid_none()
    };
}
function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: UserStatus;
    appRole: AppUserRole;
    name: string;
    createdAt: Time;
    email: string;
}): {
    id: string;
    status: _UserStatus;
    appRole: _AppUserRole;
    name: string;
    createdAt: _Time;
    email: string;
} {
    return {
        id: value.id,
        status: to_candid_UserStatus_n69(_uploadFile, _downloadFile, value.status),
        appRole: to_candid_AppUserRole_n71(_uploadFile, _downloadFile, value.appRole),
        name: value.name,
        createdAt: value.createdAt,
        email: value.email
    };
}
function to_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: EventStatus;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: EventCategory;
    eventDate: Time;
    supportedCurrencies: Array<string>;
}): {
    id: string;
    status: _EventStatus;
    baseCurrency: string;
    title: string;
    country: string;
    venue: string;
    city: string;
    tags: Array<string>;
    description: string;
    multiCurrencyEnabled: boolean;
    coverImage: string;
    vendorId: string;
    category: _EventCategory;
    eventDate: _Time;
    supportedCurrencies: Array<string>;
} {
    return {
        id: value.id,
        status: to_candid_EventStatus_n75(_uploadFile, _downloadFile, value.status),
        baseCurrency: value.baseCurrency,
        title: value.title,
        country: value.country,
        venue: value.venue,
        city: value.city,
        tags: value.tags,
        description: value.description,
        multiCurrencyEnabled: value.multiCurrencyEnabled,
        coverImage: value.coverImage,
        vendorId: value.vendorId,
        category: to_candid_EventCategory_n3(_uploadFile, _downloadFile, value.category),
        eventDate: value.eventDate,
        supportedCurrencies: value.supportedCurrencies
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TicketType): {
    numberedSeat: null;
} | {
    generalAdmission: null;
} | {
    timeSlot: null;
} {
    return value == TicketType.numberedSeat ? {
        numberedSeat: null
    } : value == TicketType.generalAdmission ? {
        generalAdmission: null
    } : value == TicketType.timeSlot ? {
        timeSlot: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    refunded: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.refunded ? {
        refunded: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActionType): {
    eventPublished: null;
} | {
    refundInitiated: null;
} | {
    paymentSucceeded: null;
} | {
    adminAction: null;
} | {
    bookingCreated: null;
} | {
    bookingConfirmed: null;
} | {
    userRegistered: null;
} | {
    vendorApproved: null;
} | {
    eventCreated: null;
} | {
    fraudHold: null;
} | {
    bookingCancelled: null;
} | {
    paymentFailed: null;
} {
    return value == ActionType.eventPublished ? {
        eventPublished: null
    } : value == ActionType.refundInitiated ? {
        refundInitiated: null
    } : value == ActionType.paymentSucceeded ? {
        paymentSucceeded: null
    } : value == ActionType.adminAction ? {
        adminAction: null
    } : value == ActionType.bookingCreated ? {
        bookingCreated: null
    } : value == ActionType.bookingConfirmed ? {
        bookingConfirmed: null
    } : value == ActionType.userRegistered ? {
        userRegistered: null
    } : value == ActionType.vendorApproved ? {
        vendorApproved: null
    } : value == ActionType.eventCreated ? {
        eventCreated: null
    } : value == ActionType.fraudHold ? {
        fraudHold: null
    } : value == ActionType.bookingCancelled ? {
        bookingCancelled: null
    } : value == ActionType.paymentFailed ? {
        paymentFailed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventCategory): {
    concert: null;
} | {
    workshop: null;
} | {
    privateEvent: null;
} | {
    conference: null;
} | {
    sports: null;
} {
    return value == EventCategory.concert ? {
        concert: null
    } : value == EventCategory.workshop ? {
        workshop: null
    } : value == EventCategory.privateEvent ? {
        privateEvent: null
    } : value == EventCategory.conference ? {
        conference: null
    } : value == EventCategory.sports ? {
        sports: null
    } : value;
}
function to_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    suspended: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.suspended ? {
        suspended: null
    } : value;
}
function to_candid_variant_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppUserRole): {
    customer: null;
} | {
    superAdmin: null;
} | {
    vendor: null;
} {
    return value == AppUserRole.customer ? {
        customer: null
    } : value == AppUserRole.superAdmin ? {
        superAdmin: null
    } : value == AppUserRole.vendor ? {
        vendor: null
    } : value;
}
function to_candid_variant_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventStatus): {
    cancelled: null;
} | {
    published: null;
} | {
    completed: null;
} | {
    draft: null;
} {
    return value == EventStatus.cancelled ? {
        cancelled: null
    } : value == EventStatus.published ? {
        published: null
    } : value == EventStatus.completed ? {
        completed: null
    } : value == EventStatus.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
